### ISSUE TITLE
Support for Visual Studio Code

### ISSUE THREAD

**Issue by straconx** [trinhanhngoc/pycharm-odoo#101]
Hi, great work with Odoo extension by Pycharm. Recentely, our company wants to move away from Pycharm (great IDE but lacks WLS support) to VSC. Only reason is delaying this change, is that there is no extension with the same functionalities. Do you have any date for the release of the version for VSC? I think the community would appreciate it.
Excellent contribution to the Odoo ecosystem. We expect news soon.
Thank you very much.

**Comment by trinhanhngoc** [comment]
> Hi, great work with Odoo extension by Pycharm. Recentely, our company wants to move away from Pycharm (great IDE but lacks WLS support) to VSC. Only reason is delaying this change, is that there is no extension with the same functionalities. Do you have any date for the release of the version for VSC? I think the community would appreciate it.
> Excellent contribution to the Odoo ecosystem. We expect news soon.
> Thank you very much.

Hi @straconx ,

An Odoo extension for VSC with similar functions has been in my plans for a long time. It's definitely a job that takes a lot of time and effort. However, I think it will be difficult to release a VSCode extension in this year.

**Comment by trinhanhngoc** [comment]
A wishlist from community: https://github.com/odoo/odoo/issues/93669

I am working hard on some possible solutions to develop VSCode extension for Odoo. I will blog about it as soon as I have a working prototype.

**Comment by straconx** [comment]
Great news. If 

> A wishlist from community: [odoo/odoo#93669](https://github.com/odoo/odoo/issues/93669)
> 
> I am working hard on some possible solutions to develop VSCode extension for Odoo. I will blog about it as soon as I have a working prototype.

Great news. As far as we can collaborate, we are at your service.

**Comment by trinhanhngoc** [comment]
Hi @straconx ,

The new Odoo extension for Visual Studio Code is now on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=trinhanhngoc.vscode-odoo). However, it will take a long time before the extension is as good as the Odoo plugin for PyCharm.
