### ISSUE TITLE
Support odoo different version folder in one project can jump to specific declaration

### ISSUE THREAD

**Issue by imlhx** [trinhanhngoc/pycharm-odoo#102]
I have two odoo source version in odoo-dev folder

odoo-dev
|___odoo-source-14.0
|___odoo-source-15.0
|___my-addons

in my-addons defined an odoo js class 

    
    odoo.define('quotation.profit_analysis', function (require) {
        'use strict';
    
    ......
    
    const FieldMany2One = require('web.relational_fields').FieldMany2One;

    ......

mouse focus on 'web.relational_fields', then ctrl+b or ctrl+left-click on mouse just jump to one "web.relational_fields" which is class defined(odoo-source-14.0 or odoo-source-15.0)，my-addons dependence on odoo-source-14.0 but I couldn't select jump to there!

**Comment by trinhanhngoc** [comment]
Hi @imlhx ,

The Odoo plugin has good support for working with multiple Odoo versions in a project. However, you will need to restructure your project for best result. This is a reference setup that you can follow for your project:

1. Open the `my-addons` folder as a new project.
2. Open the `odoo-source-14.0` folder and choose **Attach** to the `my-addons` project.
3. Open the `odoo-source-15.0` folder and choose **Attach** to the `my-addons` project.
4. Open **Project Dependencies Setting** (https://www.jetbrains.com/help/pycharm/project-dependencies.html) and set the dependencies for the `my-addons` project is the `odoo-source-14.0` project.

With the above setup, you can work with multiple Odoo versions in a single PyCharm window, the Odoo plugin will respect the project and its dependencies when resolving symbol references. Many of my colleagues are also using this setup scheme.
