### ISSUE TITLE
Embed odoo-stubs

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#109]
Embedded [odoo-stubs](https://github.com/odoo-ide/odoo-stubs) makes the setup process simpler. This also fixes many issues caused by missing `odoo-stubs` or `odoo-stubs` is incorrectly setup in the project.

**Comment by jcfernandez-890825** [comment]
So do we remove odoo-stub as attachment from Odoo projects?

**Comment by trinhanhngoc** [comment]
> So do we remove odoo-stub as attachment from Odoo projects?

Yes. After updating the Odoo plugin to the version 2023.7.0, you should remove the `odoo-stubs` that you added manually.
https://odoo-ide.com/blog/news-1/pycharm-odoo-2023-7-18
