### ISSUE TITLE
Support XML ID references for data-customize-website-views attribute of we-checkbox

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#138]
https://github.com/odoo/odoo/blob/c2894badde66a15c3a2fd2a91a2306ae8d1c8138/addons/website/views/snippets/snippets.xml#L818
<img width="856" alt="image" src="https://user-images.githubusercontent.com/11208291/190294504-5cf85a88-43a0-42bd-a853-4db924764e49.png">

The plugin currently supports XML ID references for `data-customize-website-views` attribute of `we-button`. Need to support `we-checkbox` as well.

cc @ngochuy97hp

**Comment by ngochuy97hp** [comment]
@trinhanhngoc sửa nhanh thế a nhỉ =)) we-checkout

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc sửa nhanh thế a nhỉ =)) we-checkout

Chắc vẫn còn bị ám ảnh trang pricing :)))

**Comment by trinhanhngoc** [comment]
Hi @ngochuy97hp 

The new version 2022.6 has been released with the support for `data-customize-website-views`.

**Comment by ngochuy97hp** [comment]
![image](https://user-images.githubusercontent.com/66666640/196575324-e3392bfb-5068-4782-a423-bd9534054cd1.png)
