### ISSUE TITLE
Support XML ID reference for t-snippet-call

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#152]
![image](https://user-images.githubusercontent.com/11208291/191689363-d7609316-c428-41be-ac57-3f95664d10ac.png)

@ngochuy97hp

**Comment by ngochuy97hp** [comment]
Thay quả screenshot đi a, trông phèn quá =))

**Comment by trinhanhngoc** [comment]
> Thay quả screenshot đi a, trông phèn quá =))

Camera xịn quá. Nhìn phát thấy ngay màn laptop quá bẩn.

**Comment by trinhanhngoc** [comment]
Hi @ngochuy97hp 

The new version 2022.6 has been released with the support for the `t-snippet-call`. You can read about it in the blog post https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-6-10
