### ISSUE TITLE
Unresolved JS module references in tests

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#163]
https://github.com/odoo/odoo/blob/2b6b0df06694e9891794e9acd120a364fd843e73/odoo/addons/base/static/tests/base_settings_tests.js#L10
<img width="796" alt="image" src="https://user-images.githubusercontent.com/11208291/192674559-dcaa0d5d-59b8-4883-8b7c-7aff66648fdd.png">

```
web
|___static
      |___src
      |___tests
```

`@web` = `web/static/src`
=> `@web/..` = `web/static`
=> `@web/../tests/helpers/utils` = `web/static/tests/helpers/utils`

@ngochuy97hp

**Comment by trinhanhngoc** [comment]
A screenshot provided by @ngochuy97hp
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/11208291/192675835-1a897a68-9706-4765-ab45-e71888940c47.png">

**Comment by trinhanhngoc** [comment]
Hi @ngochuy97hp

The new version 2022.7 has been released with the fix for this issue. You can learn more at https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-7-11.

**Comment by ngochuy97hp** [comment]
Ok bro
