### ISSUE TITLE
Type hint for recordset values

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#194]
Quick question, using the new type hint feature, how can I define var `m2x_dct_lst` type as a dictionary list to be used for `m2x.create.edit.option` record creation? I wanted to use code completion while creating this list comprehension, but failed.

```python
from odoo import SUPERUSER_ID
from odoo.api import Environment
from odoo.sql_db import Cursor

env = Environment(Cursor('pool', 'dbname', 'dsn'), SUPERUSER_ID, {})
self = env['res.users']


fld_rs = self.env['ir.model.fields'].search([
    ('relation', 'in', ('product.product', 'product.template')),
    ('ttype', 'in', ('many2many', 'many2one')),
])

m2x_dct_lst = [
    {
        'field_id': fld.id,
        'model_id': fld.model_id.id,
        'option_create': 'force_false',
        'option_create_edit': 'force_false',
        'option_create_edit_wizard': False,
    }
    for fld in fld_rs
]  # type: list[dict]

self.env['m2x.create.edit.option'].search([]).unlink()
self.env['m2x.create.edit.option'].create(m2x_dct_lst)

self.env.cr.commit()

```

_Originally posted by @jcfernandez-890825 in https://github.com/odoo-ide/pycharm-odoo/issues/78#issuecomment-1285544715_

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 @eselimsen @mrm-david

Because #12 is done, we can continue the discussion on how we can get type hints for recordset values.

**Comment by jcfernandez-890825** [comment]
Since this is working when declared inside the `create/new` method, is it possible for the plugin to look up for the closest variable definition and enable code completion there? 

Again, 0 experience with plugin developing for Pycharm, so I'm just throwing stones at the dark hehe.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
I think using magics like `odoo.model`, `odoo.model_dict`, `odoo.model_multi` (would help on #105 ?) may be a good idea, it would also be consistent with new type hinting.
:thinking:

**Comment by trinhanhngoc** [comment]
Hi everyone. Thank you all for your suggestions. I am going to implement the following magics for the next version 2022.7:

### Two ways to annotate a record values
```python
# This syntax is recommended for Python >= 3.9 because it makes a good fallback for unsupported IDEs.
from typing import Annotated
vals1: Annotated[dict, 'odoo.model_dict.res_partner'] = {}

# This alternative syntax is more concise but it will confuse unsupported IDEs.
vals2: 'odoo.model_dict.res_partner' = {}
``` 

### Supported contexts
```python
# 1: variable declaration
vals: 'odoo.model_dict.res_partner' = {...}

# 2: function return type
def _prepare_partner_values() -> 'odoo.model_dict.res_partner':
    return {...}

# 3: dict access
vals[...]
vals.update({...})
vals.update(**fnames)
```

### Update

`odoo.values.*` will be used instead of `odoo.model_dict.*`

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
These look exciting as always, I really loved these magics.

Thanks for the great work!

**Comment by eselimsen** [comment]
Also, one more question (hope not messing up contexts): do we have some sort of "self" support, for referring "self" model?

**Comment by trinhanhngoc** [comment]
> Also, one more question (hope not messing up contexts): do we have some sort of "self" support, for referring "self" model?

Hi @eselimsen.

Can you provide any use cases or code samples (in the Odoo source code for example) where "self" is applicable?

**Comment by eselimsen** [comment]
> Can you provide any use cases or code samples (in the Odoo source code for example) where "self" is applicable?
Like:
```python
class Model(models.Model):
    _name = "some.model"

    def get_record(self, partner_id: Union[int, "odoo.model.res_partner"]): -> "odoo.model_self"  # Any shortcut here?
        """Return some.model records for given partner_id."""
```

**Comment by trinhanhngoc** [comment]
> > Can you provide any use cases or code samples (in the Odoo source code for example) where "self" is applicable?
> > Like:
> 
> ```python
> class Model(models.Model):
>     _name = "some.model"
> 
>     def get_record(self, partner_id: Union[int, "odoo.model.res_partner"]): -> "odoo.model_self"  # Any shortcut here?
>         """Return some.model records for given partner_id."""
> ```

You can already achieve that using Python's built-in features:

- Using `TypeVar` (https://docs.python.org/3/library/typing.html#typing.TypeVar). I just discovered that this is not working for model classes. I will fix it in the next version.

```python
from typing import TypeVar

_T = TypeVar('_T')

class Model(models.Model):
    _name = "some.model"

    def get_record(self: _T, partner_id): -> _T
        """Return some.model records for given partner_id."""
```

- Using `Self` in Python >= 3.11 (https://docs.python.org/3/library/typing.html#typing.Self). Supported in PyCharm 2022.3 (https://blog.jetbrains.com/pycharm/2022/11/2022-3-eap-4-2/#Self_type).

```python
from typing import Self

class Model(models.Model):
    _name = "some.model"

    def get_record(self, partner_id): -> Self
        """Return some.model records for given partner_id."""
```

**Comment by eselimsen** [comment]
> * Using `Self` in Python >= 3.11 (https://docs.python.org/3/library/typing.html#typing.Self). Supported in PyCharm 2022.3 (https://blog.jetbrains.com/pycharm/2022/11/2022-3-eap-4-2/#Self_type).
> 
> ```python
> from typing import Self
> 
> class Model(models.Model):
>     _name = "some.model"
> 
>

`Self` looks good, I was excited for that but, as you said it is supported after 3.11, so guess I'll have to wait for that for a while.
:)

Thanks for the reply

**Comment by trinhanhngoc** [comment]
Hi all!

The new version 2022.7 has been released with this improvement. You can learn more at https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-7-11. I will continue the type hint story with https://github.com/odoo-ide/pycharm-odoo/issues/207 in the next version. Thank you all!

**Comment by jcfernandez-890825** [comment]
Just used `odoo.values.product_template` in a method that clones/copies `product.template` BoM and overrides specific field value. This is the bomb, I whish @fpodoo enforces use of your plugin as mandatory on every class/method/function/"var typing" docstring. This feature will help a lot.

Once again, may wealth and health be with you and may Odoo and your plugin becomes the best tools for mankind.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 

I tried this one today, and it is fascinating!
Combined with all other amazing improvements made with this release (including `odoo.model|values` completion), I'm just amazed how far you've gone about the plugin, especially in type awareness. To be honest, I didn't expect this feature this soon.

I would like to thank and celebrate you for the success on the plugin once again, it is a must have for anything-Odoo, and I recommend it to anyone working on Odoo.

:clap: :confetti_ball:

**Comment by eselimsen** [comment]
I also had a crazy idea I wanted to share:

As this plugin came this far, it knows a lot about Odoo, its behavior, typing etc, maybe it would be possible to make a static analyzer using it?

Just imagine putting this knowledge in your CI/CD and QA flows, pre-commit...
We can have Odoo-aware tests, and static analyzers on GitHub/GitLab, without hassle to configure dbs etc?

It may be just a dream now, but considering your velocity, maybe not far?
:D

**Comment by trinhanhngoc** [comment]
> I also had a crazy idea I wanted to share:
> 
> As this plugin came this far, it knows a lot about Odoo, its behavior, typing etc, maybe it would be possible to make a static analyzer using it?
> 
> Just imagine putting this knowledge in your CI/CD and QA flows, pre-commit... We can have Odoo-aware tests, and static analyzers on GitHub/GitLab, without hassle to configure dbs etc?
> 
> It may be just a dream now, but considering your velocity, maybe not far? :D

Hi @eselimsen 

Yeah! That's exactly what I have been thinking about for a long time. Do you know Qodana (https://www.jetbrains.com/qodana/)? That is the starting point!

**Comment by eselimsen** [comment]
> > I also had a crazy idea I wanted to share:
> > As this plugin came this far, it knows a lot about Odoo, its behavior, typing etc, maybe it would be possible to make a static analyzer using it?
> > Just imagine putting this knowledge in your CI/CD and QA flows, pre-commit... We can have Odoo-aware tests, and static analyzers on GitHub/GitLab, without hassle to configure dbs etc?
> > It may be just a dream now, but considering your velocity, maybe not far? :D
> 
> Hi @eselimsen
> 
> Yeah! That's exactly what I have been thinking about for a long time. Do you know Qodana (https://www.jetbrains.com/qodana/)? That is the starting point!

Thanks for the heads-up, I saw that a while ago, looks promising, but, I guess it is still EAP and pricing yet to be settled, I'll have an eye on it :eyes: .

It is good to know it is within your radar, and you share the same idea, I think such a tool would be really helpful, maybe as a service, or some Python package you can with pylint or something...

Whatever it is, looking forward for it!

**Comment by trinhanhngoc** [comment]
@eselimsen  By the way, I also want to share a litle bit of my short-term and long-term plans for Odoo IDE:

-  Short-term
    -  Constantly improving the Odoo plugin for PyCharm to make the best coding experience.
    -  Release a new Odoo extension for [Visual Studio Code (VSCode)](https://code.visualstudio.com) with similar features.
    -  Release a new Odoo plugin for [JetBrains Fleet](https://www.jetbrains.com/fleet) with similar features.
- Long-term
    - Constantly improving the Odoo integration on the supported IDEs (PyCharm, VSCode, Fleet).
    - Bring the Odoo Language Server used for VSCode to other IDEs/Text Editors (Eclipse IDE, Sublime Text, Vim,...).

I know this journey is full of challenges but it's exactly what I'm passionate about.

**Comment by eselimsen** [comment]
> @eselimsen By the way, I also want to share a litle bit of my short-term and long-term plans for Odoo IDE:
> 
> * Short-term
>   
>   * Constantly improving the Odoo plugin for PyCharm to make the best coding experience.
>   * Release a new Odoo extension for [Visual Studio Code (VSCode)](https://code.visualstudio.com) with similar features.
>   * Release a new Odoo plugin for [JetBrains Fleet](https://www.jetbrains.com/fleet) with similar features.
> * Long-term
>   
>   * Constantly improving the Odoo integration on the supported IDEs (PyCharm, VSCode, Fleet).
>   * Bring the Odoo Language Server used for VSCode to other IDEs/Text Editors (Eclipse IDE, Sublime Text, Vim,...).
> 
> I know this journey is full of challenges but it's exactly what I'm passionate about.

Great, thanks for the info, good to know what's upcoming.
VScode and JB Fleet looks promising, as there's a rising trend for CDEs, and how VS Code is more popular on web IDEs.

Looking forward for more, thanks for this plugin again!

**Comment by tsabi** [comment]
> Hi all!
> 
> The new version 2022.7 has been released with this improvement. You can learn more at https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-7-11. I will continue the type hint story with #207 in the next version. Thank you all!

File Not Found error. Why did you removed the blog posts? :(

**Comment by trinhanhngoc** [comment]
> > Hi all!
> > The new version 2022.7 has been released with this improvement. You can learn more at https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-7-11. I will continue the type hint story with #207 in the next version. Thank you all!
> 
> File Not Found error. Why did you removed the blog posts? :(

Sorry, you can read the documentation at https://github.com/odoo-ide/pycharm-odoo/wiki/Odoo-Type-Hints
