### ISSUE TITLE
method in compute_sudo is not clickable

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#218]
can'tclick-follow on method name specified for compute_sudo field definition attribute

**Comment by trinhanhngoc** [comment]
Hi @jerzyk ,

Can you provide screenshots for this?

**Comment by trinhanhngoc** [comment]
Hi @jerzyk ,

Since `compute_sudo` is a boolean attribute, I guess what you mean is the `compute` attribute. This is currently working fine.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/11208291/202832631-d04774f9-7142-4541-96ac-2cc4eec7b56a.png">

**Comment by jerzyk** [comment]
@trinhanhngoc you are 100% right, that was in a odoo module done by hindu developers... and while debugging I've seen such a construct
then I've reported error without checking if this is ok, so sorry - closing this as non-issue
