### ISSUE TITLE
[16] x2many field inspection in pycharm debugger

### ISSUE THREAD

**Issue by auyeung112002** [trinhanhngoc/pycharm-odoo#219]
![image](https://user-images.githubusercontent.com/8391358/202667581-686cd823-38a7-4180-8e32-2b044364d6e3.png)

Above is a screen cap of pycharm debugger in V15, this work perfectly.
But in V16 it breaks.

**Comment by trinhanhngoc** [comment]
Hi @auyeung112002 ,

Have you installed [pydevd-odoo](https://github.com/odoo-ide/pydevd-odoo) in your python environment for Odoo 16? Can you take a screenshot of the debugger in Odoo 16?

**Comment by auyeung112002** [comment]
@trinhanhngoc Oh, I forgot to install pydevd-odoo in V16 venv. It works after installation. Thanks
