### ISSUE TITLE
For fields.Selection, find the function/method when written as str

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#23]
At least for [v13](https://www.odoo.com/documentation/13.0/developer/reference/addons/orm.html#odoo.fields.Selection) and [v14](https://www.odoo.com/documentation/14.0/developer/reference/addons/orm.html#odoo.fields.Selection), `fields.Selection` can use a `str` for `selection (list(tuple(str,str)) or callable or str)` parameter:
![Screenshot from 2021-09-14 19-08-17](https://user-images.githubusercontent.com/28876647/133345408-f9bdff99-0287-41d0-9b0b-419abb8d2f33.png)

If possible, can we get the search feature that `compute` parameter has?

**Comment by trinhanhngoc** [comment]
Thank you. Implemented in the next version 2021.2.6.
