### ISSUE TITLE
Name auto-completion and jump to source with "CTRL+Right-Click" when creating an "http.Response"

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#24]
When creating an `http.Response(template=..., qcontext={...})`
![Screenshot from 2021-09-17 06-55-50](https://user-images.githubusercontent.com/28876647/133771589-305bfa44-b7ae-40fb-bcfd-bda52e698a2b.png)

There's not name auto-completion 
![Screenshot from 2021-09-17 07-01-08](https://user-images.githubusercontent.com/28876647/133772201-7a2c909d-1e74-4964-87b1-3c0bc1ae3e36.png)

and jump to source with "CTRL+Right-Click".
![Screenshot from 2021-09-17 06-59-04](https://user-images.githubusercontent.com/28876647/133771997-77ff5a24-aedf-4f84-8bcd-2f160492dc4c.png)

And you can't use `http.request.render(template, qcontext=None, lazy=True, **kw)` when dealing with JSON routes like this one:
![Screenshot from 2021-09-17 07-04-06](https://user-images.githubusercontent.com/28876647/133772504-63d07735-a0c8-4c44-a1bf-a59170072e65.png)

**Comment by trinhanhngoc** [comment]
Thank you. Implemented in the next version 2021.2.6.
