### ISSUE TITLE
XPath domain attribute extension should use related model

### ISSUE THREAD

**Issue by eselimsen** [trinhanhngoc/pycharm-odoo#241]
Hi @trinhanhngoc 
When overriding domain of related fields, with `attribute` tag in views, PyCharm thinks it is extending the original model of view, instead of related  field.
Would it be possible to fix this issue?

Example:
![Screenshot_20221129_212635](https://user-images.githubusercontent.com/61320931/204615104-f712a7a8-5c92-4acd-9442-ede49df00904.png)

**Comment by trinhanhngoc** [comment]
Hi @eselimsen 

This issue has just been fixed in the new version 2022.7.2. Please wait for a few hours before you can receive the update from Jetbrains Marketplace. Thank you so much for reporting!

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Thank you for such a quick fix!

**Comment by trinhanhngoc** [comment]
Thank @eselimsen. The new version will also fix a similar issue when the xpath position is `inside` because inside a field there are often subviews. In that case, fields in the subviews must also belong to the related model (comodel).
