### ISSUE TITLE
Show class names for model "Choose Declaration" popup

### ISSUE THREAD

**Issue by eselimsen** [trinhanhngoc/pycharm-odoo#242]
Hi
Not a huge issue, but is it possible to show "Choose Declaration" popup for models in the same way as you're doing for fields?

Fields include class name, helps when many modules inherit with similar names:
![Screenshot_20221129_212854-1](https://user-images.githubusercontent.com/61320931/204615836-2b5476e8-5442-4a1f-b136-b0f2464c5186.png)

Models don't have class name, harder to follow:
![Screenshot_20221129_212840](https://user-images.githubusercontent.com/61320931/204615907-fb746950-f1e6-4b69-961f-601df85f5d44.png)

Thanks

**Comment by trinhanhngoc** [comment]
Hi @eselimsen ,

Thanks for your suggestions. The new version 2022.7.4 has been released with this improvement!

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Works just perfect, thanks!
