### ISSUE TITLE
Attributes of xpath are sometimes marked as invalid attributes

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#255]
https://github.com/odoo/odoo/blob/45b5bbfcf7e154e97cbc52013f874208998f573f/addons/sale/views/sale_portal_templates.xml#L22
<img width="960" alt="image" src="https://user-images.githubusercontent.com/11208291/206152012-73056116-3b2a-46d0-a1ac-91f94b7e7ecb.png">

**Comment by jcfernandez-890825** [comment]
+1

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2022.7.3 has been released to address this issue.
