### ISSUE TITLE
No suggestions for module name on env

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#265]
I was typing `sale.order.line`, waiting for the autocomplete list when this issue came out.

![image](https://user-images.githubusercontent.com/28876647/208613183-240095f1-fa24-426b-a09c-c53ecd4f4a67.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The model `sale.order.line` is defined in the module `sale`. Try to check if your module already depends on `sale`.

**Comment by jcfernandez-890825** [comment]
I think this is happening because I have this code in a non-conventional file path.

**Comment by trinhanhngoc** [comment]
> I think this is happening because I have this code in a non-conventional file path.

Fortunately, it's not the plugin's fault =))
