### ISSUE TITLE
Unresolved reference on user_has_groups for multiple groups

### ISSUE THREAD

**Issue by eselimsen** [trinhanhngoc/pycharm-odoo#271]
Hi @trinhanhngoc, hope you're doing well
As you know, `Model.user_has_groups` supports comma-separated group names for checking multiple groups at once, but plugin tries to resolve the string as a whole, giving unresolved reference error.
Would it be possible to fix it?

_stock/models/stock_picking.py on v15:_

![Screenshot_20221220_213507](https://user-images.githubusercontent.com/61320931/208740878-359d54de-968a-4ccb-b4be-dbfa33be89af.png)

Thanks

**Comment by trinhanhngoc** [comment]
Hi @eselimsen 

Thank you for reporting!. I am working on a fix for this issue. Please wait for the new version with the fix tomorrow.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Thanks for the quick reply as always, looking forward for the next version.

**Comment by trinhanhngoc** [comment]
Hi @eselimsen 

The new version 2022.7.5 has been released with the fix for this issue.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc 
Thanks for the quick fix, works perfect now!
