### ISSUE TITLE
A setting for Editor Tabs names

### ISSUE THREAD

**Issue by maciej-wichowski** [trinhanhngoc/pycharm-odoo#277]
Hi! I noticed Editor Tab names show module paths. Is there an option to show filenames only? If not, could you add one?
![obraz](https://user-images.githubusercontent.com/24193679/209815993-10963cf6-7055-4083-98f7-85f5627170d5.png)

**Comment by trinhanhngoc** [comment]
Hi @maciej-wichowski 

Currently, there is no such option. I will add it in the next version.

**Comment by trinhanhngoc** [comment]
Hi @maciej-wichowski 

The new version 2022.7.7 has been released to address this issue. Editor tab names no longer take up too much space.
