### ISSUE TITLE
Unresolved references on OCA module

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#288]
https://github.com/OCA/manufacture/blob/134d2d17a3ed9e62bab7b7e7f156e80b46ffe4e4/mrp_bom_location/report/bom_structure.py
![image](https://user-images.githubusercontent.com/28876647/211520506-b9e0be62-d4e5-4604-9b12-3bdd40c03b67.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The cause of this issue is the same as in #290 , PyCharm infers the type of the `lines` dict in `ReportBomStructure._get_bom()` incorrectly.

**Comment by trinhanhngoc** [comment]
Upstream PyCharm issue: https://youtrack.jetbrains.com/issue/PY-58545/Allow-TypedDict-inference-for-dict-literal-expressions-with-more-than-10-keys

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The new version 2023.2.0 has been released to address this issue.
