### ISSUE TITLE
Lots of unresolved references in "report.mrp.report_bom_structure" model

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#290]
https://github.com/exigo-is/odoo_enterprise/blob/be427dcf65e98b248c6703da9989179a554ad5b0/odoo/addons/mrp/report/mrp_report_bom_structure.py
![image](https://user-images.githubusercontent.com/28876647/211522919-c3197c41-dd6b-4395-8d26-09fd092f9f6d.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825,

There seem to be problems with type inference for dict literal expressions. 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/11208291/211527277-7f9b55f8-46bc-46f7-b2a4-c768c806cd35.png">


Thanks for the report. Happy new year :)

**Comment by trinhanhngoc** [comment]
Upstream PyCharm issue: https://youtrack.jetbrains.com/issue/PY-58545/Allow-TypedDict-inference-for-dict-literal-expressions-with-more-than-10-keys

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The new version 2023.2.0 has been released to address this issue.
