### ISSUE TITLE
Unresolved attribute reference 'selection' for class 'Field' 

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#298]
https://github.com/exigo-is/odoo_enterprise/blob/be427dcf65e98b248c6703da9989179a554ad5b0/odoo/addons/base/models/ir_model.py#L1202

odoo.addons.base.models.ir_model.IrModelSelection._reflect_selections

![image](https://user-images.githubusercontent.com/28876647/211840896-66ef5355-824f-47d4-aae6-afeb22234200.png)

**Comment by trinhanhngoc** [comment]
Related issue: #164

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Before the issue #164 is addressed, I will update odoo-stubs as a workaround to get rid of these errors.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2023.2.1 just released with the fix for this issue.

**Comment by jcfernandez-890825** [comment]
And do we still need the patch you did on odoo-stub regarding this?

**Comment by trinhanhngoc** [comment]
> And do we still need the patch you did on odoo-stub regarding this?

Sorry, I forgot to note that. You don't need to update `odoo-stubs`. At first I thought that a simple patch to `odoo-stubs` would be enough to fix this, but it is not.
