### ISSUE TITLE
Element img doesn't have required attribute src

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#320]
Search on Odoo code for `<img t-attf-src=`.

`odoo/addons/website_sale_comparison/views/website_sale_comparison_template.xml`
![image](https://user-images.githubusercontent.com/28876647/220327431-d0f5701c-5562-4b3c-9e7e-8bed038dd7e4.png)

**Comment by trinhanhngoc** [comment]
Same https://github.com/odoo-ide/pycharm-odoo/issues/284.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2023.3.1 has been released to address this issue.

**Comment by jcfernandez-890825** [comment]
Is working, as usual thanks a lot for creating such an amazing plugin. You deserve everything that is good in life.
