### ISSUE TITLE
"Cannot find declaration to go to" for model on field on XML "ir.actions.report"

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#321]
Odoov15
`odoo/addons/sale/report/sale_report.xml`
![image](https://user-images.githubusercontent.com/28876647/220330278-f73cb5d6-a6fd-4d2e-99ee-38dae86b6096.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 Thanks for the report. This will be addressed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , the new version 2023.2.5 has been released to address this issue.
