### ISSUE TITLE
"Cannot find declaration to go to" for t-field

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#322]
Odoov15
`odoo/addons/product/report/product_packaging.xml`
![image](https://user-images.githubusercontent.com/28876647/220331297-79b84d9c-cab3-4aff-a7a7-a14b3067a662.png)

**Comment by trinhanhngoc** [comment]
Same https://github.com/odoo-ide/pycharm-odoo/issues/232.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 
Any updates?

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc Any updates?

I plan to address this issue in early 2024. Stay tuned!

**Comment by trinhanhngoc** [comment]
Hello @jcfernandez-890825 ,

The new version 2024.4.0 has been released  to address this issue.
