### ISSUE TITLE
false positive warning on model.search() with count=True

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#323]
when search is called with count=True - it's result is int - this generates false positive warning: `expecting _ModelT not int`

**Comment by trinhanhngoc** [comment]
Hi @jerzyk . Thanks for the report!. This will be addressed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @jerzyk , the new version 2023.2.5 has been released with the fix for this issue.

**Comment by jerzyk** [comment]
it's working! thanks!
