### ISSUE TITLE
No completion for domain if the domain is in a string spread on multiple lines

### ISSUE THREAD

**Issue by mrm-david** [trinhanhngoc/pycharm-odoo#324]
Example : 
```python
        recs = self.search(
            '[("field1", "=", False),'
            '("field2.field2a", "=", True),'
            '("field3", "!=", field2.field2b.field2ba),'
            '("field4", "!=", True)]'
        )
```

Note that AFAIK, the domain must be passed as a string to be able to test this `("field3", "!=", field2.field2b.field2ba)`

**Comment by mrm-david** [comment]
Passing domain as a string works in field definitions ( domain=…) but apparently not in the search method.

**Comment by trinhanhngoc** [comment]
> Passing domain as a string works in field definitions ( domain=…) but apparently not in the search method.

I just checked the definition of the `search()` method. Looks like Odoo only supports domain expression in the form of a list or a tuple.

**Comment by mrm-david** [comment]
Do you know if there's a way to do a `.search([("field1","=",field2)])` ?   

The only workaround I see is add a computed stored boolean field that computes field1==field2 and search on tha field, but it's sad to have to do that.

**Comment by trinhanhngoc** [comment]
If the search domain is simple enough, I think we also can use `cr.execute(sql)`.
