### ISSUE TITLE
Missing usages for computed fields

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#337]
Pycharm is reporting that field "dropp_apikey" doesn't have any usages, yet it's used twice on its computed method:
![image](https://user-images.githubusercontent.com/28876647/225875711-e638a3a1-5c78-4f37-9ed3-f7a393167d70.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , thank you for the report. This issue will be addressed in the next release.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2023.3.3 has been released with the fix for this issue.
