### ISSUE TITLE
Unresolved model in newly created file

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#338]
Steps to produce the issue:

1. Open an existing model file in the `account` module.
2. Also in that module, create a new model file.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/11208291/226269167-fb9c50f9-2da2-498c-8169-74ce1935435f.png">

**Comment by ngochuy97hp** [comment]
Ngon em cũng bị lỗi này

**Comment by trinhanhngoc** [comment]
> Ngon em cũng bị lỗi này

Lỗi này bắt đầu có cách đây 543 ngày =))

**Comment by ngochuy97hp** [comment]
Không hiểu kiểu gì lúc đầu đỏ nhưng mở nhiều file tí quay lại thì lại xanh =))

**Comment by trinhanhngoc** [comment]
> Không hiểu kiểu gì lúc đầu đỏ nhưng mở nhiều file tí quay lại thì lại xanh =))

Đó là do lỗi liên quan đến validate cache khi anh cải tiến để sử dụng cache lâu hơn từ 543 ngày trước. Chỉ cần chú sửa file manifest bất kì thì nó mới recompute lại. Nên cơ bản thì anh fix nó đơn giản là cứ có sự kiện thêm/xoá/đổi tên file thì nó sẽ recompute lại. Giống hệt Odoo =)).
