### ISSUE TITLE
[BUG] Plugin is not providing model suggestion list when getting model from self.env

### ISSUE THREAD

**Issue by pnajman-modoolar** [trinhanhngoc/pycharm-odoo#340]
PyCharm version 2023.1
Odoo plugin version: 2023.3.4.231

![Screenshot from 2023-04-01 07-31-09](https://user-images.githubusercontent.com/28532306/229267515-65aafb87-6f75-4e39-ac26-dba757070a9a.png)

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar , you need to attach [odoo-stubs](https://github.com/odoo-ide/odoo-stubs) to your project for the feature to work. In the next version, I will make it work even in projects without `odoo-stubs`.

**Comment by pnajman-modoolar** [comment]
> Hi @pnajman-modoolar , you need to attach [odoo-stubs](https://github.com/odoo-ide/odoo-stubs) to your project for the feature to work. In the next version, I will make it work even in projects without `odoo-stubs`.

Hi @trinhanhngoc , 

Yes, it's attached. Everything else works OK except this.

**Comment by trinhanhngoc** [comment]
@pnajman-modoolar , do you get `env` in the completion results like in the following screenshot?

<img width="686" alt="image" src="https://user-images.githubusercontent.com/11208291/229277487-712b8aab-64aa-47a8-b45e-c117499c203c.png">

**Comment by pnajman-modoolar** [comment]
@trinhanhngoc As you can see stubs are registered:

![Selection_899](https://user-images.githubusercontent.com/28532306/229277665-6b82df8f-88b1-4555-9609-27b7cd3dd2df.png)

**Comment by pnajman-modoolar** [comment]
Hi, @trinhanhngoc 

Apparently there was a glitch or something.
Once I removed all source folders and added them back it started to work properly.

Maybe the glitch was due to the PyCharm update as last night I switched to the new version: 2023.1

**Comment by trinhanhngoc** [comment]
@pnajman-modoolar Good news! You confused me for a while =))

**Comment by pnajman-modoolar** [comment]
Hi @trinhanhngoc

I have this issue again. 
Tried removing and adding odoo-stubs like the last time, restarting IDE, but with no luck this time :(

After typing `self.env` i get following completion results:
![Selection_902](https://user-images.githubusercontent.com/28532306/229372070-f2fbef28-baa0-434f-9c45-268d7e0a91bc.png)

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar, today I will publish a new plugin version. I hope it will fix your issue.

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar , the new version 2023.4.0 has been released. You can update the Odoo plugin to see if it fixes your issue.

**Comment by pnajman-modoolar** [comment]
Hi @trinhanhngoc .

Yes I'm using the latest PyCharm version 2023.1.
Plugin update solved the issue.

Thanks,
Petar

**Comment by pnajman-modoolar** [comment]
Hi @trinhanhngoc I've noticed that the latest plugin update restarted trial period. I now have additional month of trial. Just wanted to let you know about the issue ...

**Comment by trinhanhngoc** [comment]
> Hi @trinhanhngoc I've noticed that the latest plugin update restarted trial period. I now have additional month of trial. Just wanted to let you know about the issue ...

Hi @pnajman-modoolar Thanks for the information. I also don't know why.

**Comment by pnajman-modoolar** [comment]
@trinhanhngoc Could be something related to the latest PyCharm version 2023.1 ...
