### ISSUE TITLE
false positive warning Unresolved attribute reference 'display_name' for class 'res.country' 

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#355]
version 2023.4.0.231

'display_name' is one of the "magic" model attributes...

**Comment by trinhanhngoc** [comment]
Hi @jerzyk , have you attached [odoo-stubs](https://github.com/odoo-ide/odoo-stubs) to your project?. The `display_name` attribute is defined in `odoo-stubs`.

**Comment by jerzyk** [comment]
yes:

<img width="727" alt="Screenshot 2023-04-11 at 09 11 14" src="https://user-images.githubusercontent.com/199073/231084263-2e9d3c28-c7da-4c28-a8f4-c3b80d72e85b.png">

**Comment by trinhanhngoc** [comment]
@jerzyk , I just setup a new project with a structure like yours but couldn't reproduce this issue.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/11208291/231089392-e7758202-53da-4934-8cfa-9abf82d9990d.png">
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/11208291/231089452-e6735b14-d57f-4349-8b82-8917dc538cef.png">
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/11208291/231090774-14060141-f979-4127-9220-2dfdaf8cdb70.png">

**Comment by jerzyk** [comment]
strange, I'll try to reset all pycharm indexes

**Comment by jerzyk** [comment]
it is now fixed... 3 things done:
* update stubs (I've had repo 2 weeks old)
* invalidate all pycharm caches
* extra restart of pycharm

can't say which one helped...
