### ISSUE TITLE
Add missing tags to commit message completion

### ISSUE THREAD

**Issue by AntoineVDV** [trinhanhngoc/pycharm-odoo#367]
Hello, I saw that version 2023.5.2 added commit message tag completion. I don't think it'll be useful as an autocomplete tool, but it might serve as quick documentation for new developers :+1: 

There are, however, two tags that Odoo developers use to better label their commits and that are missing from the list:
- [PERF]: "for performance fixes"
- [CLN]: "for cosmetic changes in code" or "for code cleanup"

These two will be added to the official Odoo guidelines later on.

**Comment by trinhanhngoc** [comment]
Hi @AntoineVDV . You're right. That's exactly my aim for that feature. I remember when I was new to Odoo development, I often forgot tags and their meaning. Thanks for your information, I will add those two tags to the list for the next version.

**Comment by trinhanhngoc** [comment]
Hi @AntoineVDV. The new version 2023.5.4 has been released with two new tags (PERF and CLN) added to commit message completion.
