### ISSUE TITLE
Cannot resolve symbol (CustomModel.method) on XML view

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#37]
I inherited a wizard model like this:
![image](https://user-images.githubusercontent.com/28876647/137763514-155b4265-a61e-4866-a41c-5faa4e799b4d.png)

And created its view like this:
![image](https://user-images.githubusercontent.com/28876647/137763838-d6568a73-ce0d-4a35-b0ca-6e00f4072592.png)

I think the problem here is that since this is a inherited primary view, and it has a different model than its ancestor. It's showing this error because `action_send_is_xml_tax_report` method is in `custom.vat.report.wizard` but not in its ancestor `vat.report.wizard`.

**Comment by trinhanhngoc** [comment]
Thank you again!. The fix will be available in the next release 2021.2.9.
