### ISSUE TITLE
[BUG] Unit Test: Selection field completion for assignment operator does not provide suggestions

### ISSUE THREAD

**Issue by pnajman-modoolar** [trinhanhngoc/pycharm-odoo#372]
Hi @trinhanhngoc ,

I've noticed that assignment operator for selection fields does not provide suggestions

![Selection_975](https://github.com/odoo-ide/pycharm-odoo/assets/28532306/5b33644c-97e4-48b6-bcab-4be54a5efe63)

However, in the same setup the comparison operator provides suggestions

![Selection_976](https://github.com/odoo-ide/pycharm-odoo/assets/28532306/c12c8645-5c2f-4703-aec6-25d7a17e38c6)

P.S.
I have properly setup my environment as per plugin instructions

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar I just checked again, it's working for me.

<img width="1204" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/ef9117a2-c651-422e-b77b-fce1947ad89b">

---

When hovering over `payment_mode`, do you see a pop-up with field information like this?:

<img width="1204" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/e87554d7-2741-4eda-be9d-45e61fa3989b">

**Comment by pnajman-modoolar** [comment]
Hi @trinhanhngoc ,

Ah, I see, you've missed the part of my comment about "Unit Tests", though it was only mentioned in the issue subject, my apologies for that.

The problem is within unit test cases.

![Selection_978](https://github.com/odoo-ide/pycharm-odoo/assets/28532306/87768220-1f49-4a02-9d8b-ee327df4c40c)

From the screenshot above you can see that the `subscription_tmpl` is a class member and actual record instance (model: `sale.order.template`) defined in one of the parent test cases.

In addition, just to differentiate, when I use `env` to create instance of the model in test case, then the assignment operator suggestions work properly.

![Selection_979](https://github.com/odoo-ide/pycharm-odoo/assets/28532306/50544d95-4856-4557-8276-0bc8bf39fe34)

Regards,
Petar

**Comment by trinhanhngoc** [comment]
@pnajman-modoolar Oh, I just reproduced this issue. Thanks for the bug report. This issue will be addressed in the next version released early next week.

**Comment by pnajman-modoolar** [comment]
Hi @trinhanhngoc ,

Closing this issue as it's resolved in the latest version.

Cheers,
Petar
