### ISSUE TITLE
Support custom auth methods for http route

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#380]
route decorator (odoo.http.route) accepts `auth` arguments that has 3 options

if you would like to add additional auth method, there is a false positive error 

you can add new methods, by adding `_auth_method_<name>` class method to ir.http model

so there is a possibility to check for valid newly defined methods

**Comment by trinhanhngoc** [comment]
@jerzyk Thanks for the information. I didn't know that Odoo has that feature. I will add support for custom auth methods in a future release.

**Comment by trinhanhngoc** [comment]
Hi @jerzyk . The new version 2023.6.2 has been released with support for custom auth methods. The Odoo plugin now also provides the ability to navigate to auth method implementations.

<img width="985" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/56c1fe51-bf12-4b30-ac4b-4bc379388c6d">

<img width="985" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/7c31c5f8-e1b4-4237-93c1-6655ba822f78">

**Comment by jerzyk** [comment]
works perfectly! thanks!
