### ISSUE TITLE
Cannot resolve symbol in XML

### ISSUE THREAD

**Issue by IJOL** [trinhanhngoc/pycharm-odoo#383]
Every xml file in my project now, as i dont remember this being an issue a week or so ago, contains multiple errors like the   ones below :
 `Cannot resolve symbol 'ir.actions.act_window'
 Cannot resolve symbol 'name'
 Cannot resolve symbol 'res_model'`

and so on, every xml file now has this kind of errors, is annoying because this complicates our precommit checks very much..
pycharm 2023.1.2 and updated plugin just few minutes ago.. odoo v10

**Comment by trinhanhngoc** [comment]
Hi @IJOL , can you provide additional information like PyCharm version, Odoo plugin version, Odoo version and screenshots of errors?

**Comment by IJOL** [comment]
Sorry, i was completing my initial report, pycharm 2023.1.2 and updated plugin just few minutes ago.. odoo v10

**Comment by IJOL** [comment]
![Captura de pantalla de 2023-06-12 11-00-18](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/2e43e2b6-8d1a-4335-beef-4994948cb14b)

**Comment by trinhanhngoc** [comment]
@IJOL Have you tried [**Invalidate caches**](https://www.jetbrains.com/help/pycharm/invalidate-caches.html)?

**Comment by IJOL** [comment]
Tried invalidate and restart without any boxes checked, and we use 3 odoo versions , v10 and v16 have the same problems  reported but  odoo v12 is not doing the same. the v12 xml opens without issues
![Captura de pantalla de 2023-06-12 11-22-17](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/0fc43361-7885-45a3-b134-5b1d0b4905a4)
![Captura de pantalla de 2023-06-12 11-22-26](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/d29c9c98-a9ca-4975-b9fe-0ea012f93033)

**Comment by trinhanhngoc** [comment]
@IJOL In this screenshot:

![](https://user-images.githubusercontent.com/3046487/245094034-0fc43361-7885-45a3-b134-5b1d0b4905a4.png)

Have you set up the `integration` module to depend (directly or indirectly) on the `queue_job` module?

**Comment by IJOL** [comment]
of course, 
![Captura de pantalla de 2023-06-12 11-50-31](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/5efa66b6-7809-47bf-ab0b-abc0094ce7c7)

**Comment by trinhanhngoc** [comment]
@IJOL Do you also get the same errors in Python files, for example:

```python
self.env['queue.job.channel'] // error: unresolved reference 'queue.job.channel'
```

**Comment by IJOL** [comment]
v10 and v16 equally failed, v12 not, all the installs configs and so on are more or less the same, they all them run a sane odoo, working as charm, no issues related to odoo in itself, i've just checked that the views in odoo source open in all three without issues, and no the queue.job.channel model is present for sure.. i can open some other xml as example that do not relate to that queue module at all

**Comment by IJOL** [comment]
![Captura de pantalla de 2023-06-12 12-03-34](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/940a5b89-7be4-42d1-b501-970d69a0295c)

**Comment by trinhanhngoc** [comment]
@IJOL This is my project structure, how about yours?

<img width="1209" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/9c6fc0e3-1324-4c5a-a09e-5df5c678cd10">

**Comment by IJOL** [comment]
![Captura de pantalla de 2023-06-12 12-44-23](https://github.com/odoo-ide/pycharm-odoo/assets/3046487/d149f9f2-09de-498d-9f19-4fc2d6c1d355)

**Comment by trinhanhngoc** [comment]
@IJOL The errors appear in the project `addons160`, which I assume depends on the project `odoo160`. If true, please check if your Project Dependencies settings are correct.

<img width="1209" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/680aaf1d-bbcd-4f56-a98d-d847f8f4c901">

**Comment by IJOL** [comment]
Ok, you nailed it, was a dependency problem,  addons100 and 160 didnt depend in the corresponding odoo1XX, but in addons120 it was correct,  many thanks, please delete all those images of my setup please , ;)..
