### ISSUE TITLE
java.lang.IllegalStateException: calculatePyModuleLoadingRank must not return null

### ISSUE THREAD

**Issue by pnajman-modoolar** [trinhanhngoc/pycharm-odoo#385]
Hi @trinhanhngoc ,

PyCharm Version: 2023.1.2
Odoo Plugin Version: 2023.6.0.231

I've just got this "IDE Internal Error" bellow.
Please let me know if you need more info from my side.

> java.lang.IllegalStateException: @NotNull method dev/ngocta/pycharm/odoo/module/OdooModuleUtils.calculatePyModuleLoadingRank must not return null
> 	at dev.ngocta.pycharm.odoo.module.OdooModuleUtils.$$$reportNull$$$0(OdooModuleUtils.java)
> 	at dev.ngocta.pycharm.odoo.module.OdooModuleUtils.calculatePyModuleLoadingRank(OdooModuleUtils.java:180)
> 	at dev.ngocta.pycharm.odoo.module.OdooModuleUtils.lambda$sortInModuleFilesByLoadingOrder$6(OdooModuleUtils.java:168)
> 	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
> 	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
> 	at java.base/java.util.TimSort.sort(TimSort.java:220)
> 	at java.base/java.util.Arrays.sort(Arrays.java:1233)
> 	at java.base/java.util.List.sort(List.java:510)
> 	at dev.ngocta.pycharm.odoo.module.OdooModuleUtils.sortInModuleFilesByLoadingOrder(OdooModuleUtils.java:168)
> 	at dev.ngocta.pycharm.odoo.module.OdooModuleUtils.sortElementByModuleLoadingOrder(OdooModuleUtils.java:140)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelIndex.getModelClassDefinitionsByName(OdooModelIndex.java:152)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelIndex.lambda$getModelClassDefinitionsByName$2(OdooModelIndex.java:165)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelIndex.getModelClassDefinitionsByName(OdooModelIndex.java:163)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getDefinitions(OdooModelClass.java:67)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.lambda$getSuperClasses$3(OdooModelClass.java:167)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getSuperClasses(OdooModelClass.java:165)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.lambda$getAncestorClasses$0(OdooModelClass.java:86)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getAncestorClasses(OdooModelClass.java:83)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.lambda$getAncestorClasses$0(OdooModelClass.java:89)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getAncestorClasses(OdooModelClass.java:83)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.lambda$getAncestorClasses$0(OdooModelClass.java:89)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getAncestorClasses(OdooModelClass.java:83)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getAncestorClasses(OdooModelClass.java:73)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.visitAncestorMembers(OdooModelClass.java:539)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.visitAncestorMembers(OdooModelClass.java:581)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.lambda$getMembers$15(OdooModelClass.java:594)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:338)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClass.getMembers(OdooModelClass.java:590)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClassType.getMembers(OdooModelClassType.java:145)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClassType.resolveMemberElements(OdooModelClassType.java:123)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClassType.resolveMember(OdooModelClassType.java:116)
> 	at dev.ngocta.pycharm.odoo.model.OdooModelClassType.resolveMember(OdooModelClassType.java:90)
> 	at com.jetbrains.python.psi.impl.references.PyQualifiedReference.resolveInner(PyQualifiedReference.java:89)
> 	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.resolveInner(OdooPyQualifiedReference.java:87)
> 	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.lambda$multiResolve$0(OdooPyQualifiedReference.java:58)
> 	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
> 	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
> 	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
> 	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.lambda$multiResolve$1(OdooPyQualifiedReference.java:58)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:311)
> 	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:322)
> 	at dev.ngocta.pycharm.odoo.python.psi.OdooPyQualifiedReference.multiResolve(OdooPyQualifiedReference.java:52)
> 	at com.jetbrains.python.psi.PyUtil.multiResolveTopPriority(PyUtil.java:511)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.tryResolvingWithAliases(PyTypingTypeProvider.java:1707)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.tryResolving(PyTypingTypeProvider.java:1696)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.resolveToQualifiedNames(PyTypingTypeProvider.java:1761)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingAnnotationInjector.isTypingLiteralArgument(PyTypingAnnotationInjector.java:112)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingAnnotationInjector.getInjectedLanguage(PyTypingAnnotationInjector.java:56)
> 	at com.jetbrains.python.codeInsight.PyInjectorBase.registerInjection(PyInjectorBase.java:43)
> 	at com.jetbrains.python.codeInsight.typing.PyTypingAnnotationInjector.registerInjection(PyTypingAnnotationInjector.java:40)
> 	at com.jetbrains.python.codeInsight.PyInjectorBase.getLanguagesToInject(PyInjectorBase.java:30)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:445)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUpInner(InjectedLanguageUtilBase.java:238)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.lambda$probeElementsUp$0(InjectedLanguageUtilBase.java:218)
> 	at com.intellij.openapi.application.impl.ReadActionCacheIml$allowInWriteAction$1.invoke(ReadActionCacheIml.kt:22)
> 	at com.intellij.openapi.application.impl.ReadActionCacheIml$allowInWriteAction$1.invoke(ReadActionCacheIml.kt:22)
> 	at com.intellij.openapi.application.impl.ReadActionCacheIml.allowInWriteAction$lambda$0(ReadActionCacheIml.kt:18)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.allowProcessingContextInWriteAction(ReadMostlyRWLock.java:204)
> 	at com.intellij.openapi.application.impl.ReadActionCacheIml.allowInWriteAction(ReadActionCacheIml.kt:18)
> 	at com.intellij.openapi.application.impl.ReadActionCacheIml.allowInWriteAction(ReadActionCacheIml.kt:22)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:217)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:159)
> 	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:329)
> 	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$processInjectedPsiFiles$6(InjectedGeneralHighlightingPass.java:171)
> 	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
> 	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
> 	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
> 	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
> 	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
> 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Cheers,
Petar

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar. Thank you for reporting the bug. This will be addressed in the next release.

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar The new version 2023.6.1 has been released with the fix for this issue.
