### ISSUE TITLE
Unresolved references in non-module files

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#395]
For every odoo project, I have a miscellaneous folder where I have a list of python files having script like things that I run using Odoo shell:
```
venv/bin/python src/odoo/odoo-bin shell [...]
```

I was gonna use one of those scripts (See `odoo15.zip` attachment) today, when I saw a lot of errors and warnings:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/1ba3c208-7e2d-4131-a526-97868682d332)

![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/5251e710-0ee2-44c3-b6dd-5a6bc62c289e)

Any ideas?

[odoo15e.zip](https://github.com/odoo-ide/pycharm-odoo/files/11816648/odoo15e.zip)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 I just attached your folder to my project. There are some unresolved reference errors but not as many as yours.

<img width="1624" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/783090f9-b422-4194-85e2-665034d86c52">

For files that are not in any modules, Odoo plugin will restrict the scope of symbol resolution to server-wide modules (base + web). I think I will improve this a bit in the next version by enlarging the scope to the project scope for better symbol resolution.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 
The thing is that I have more of this kind of files in this same folder, and I only get this errors when using the module model. For my purposes, the scope thing you mentioned only meant that I didn't get auto-complete suggestions when doing a `self.env['some.module']`, but Copilot helped with that regard.
Nevertheless, there's still the not reference found for module model.
🤔

**Comment by trinhanhngoc** [comment]
While investigating this issue, I discovered an interesting bug in the Odoo plugin. It's interesting to discover bugs that have been around for a long time.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2023.6.3 just released with various improvements for this issue.
