### ISSUE TITLE
False positive unresolved reference

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#399]
open R14 addons/sale/models/sale.py line 1341:

```
                if line.product_id.type in ('consu', 'product'):
```

<img width="824" alt="Screenshot 2023-07-12 at 14 45 57" src="https://github.com/odoo-ide/pycharm-odoo/assets/199073/d1f3e4af-13c5-4b0c-b2a7-369baa37b677">

'product' is defined in product module, sale module has product indirect dependency (sale->payment->account->product)

**Comment by trinhanhngoc** [comment]
Hi @jerzyk , I just checked this. I think the unresolved reference report is correct. The `product` value is defined in the `stock` module. The `product` module defines only two values: `consu` and `service`.

product/models/product_template.py
<img width="1624" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/6f6ed280-8075-458a-adc6-4f4a65578213">

stock/models/product.py
<img width="1624" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/aedeb115-4d23-4ffe-8e5a-4b0c5aeb5ec7">

**Comment by jerzyk** [comment]
you are right! so I'll report this as an error to odoo
