### ISSUE TITLE
The red zig-zag underlines indicating errors due to unresolved imports to Odoo modules

### ISSUE THREAD

**Issue by cimbaIG** [trinhanhngoc/pycharm-odoo#408]
I purchased license and activated plugin inside PyCharm. However, I am still getting the red zig-zag underlines indicating errors due to unresolved imports to Odoo modules.

It looks like this:
<img width="539" alt="Screenshot 2023-08-24 at 11 32 10" src="https://github.com/odoo-ide/pycharm-odoo/assets/15960342/e350620a-1969-4e61-b80c-fb6b2315dfed">

How to solve this issue? 

Thank you!

**Comment by trinhanhngoc** [comment]
Hello @cimbaIG . These errors are most likely related to your project structure. Can you open `Settings > Project > Project Structure` and take a screenshot?

<img width="1091" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/06969884-0aad-49c9-ab9e-500a10265d10">

**Comment by cimbaIG** [comment]
Hi @trinhanhngoc!

Here is the screenshot of my project structure, as requested.

<img width="985" alt="Screenshot 2023-08-24 at 12 42 53" src="https://github.com/odoo-ide/pycharm-odoo/assets/15960342/4ad0c60e-04e1-4514-b776-103fa710c1c1">

**Comment by trinhanhngoc** [comment]
@cimbaIG Because the odoo source code folder is not the root folder in your project (the root folder is `Odoo16`), you need to mark the odoo source code folder as `Sources`:


<img width="985" alt="pycharm" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/0af86e42-1593-4575-bc41-eb8a94e3854f">

**Comment by cimbaIG** [comment]
@trinhanhngoc Thank you for solving this issue for me! 

I've started using PyCharm as my first IDE recently so I am obviously a PyCharm rookie. :)

I will close this issue now.

Best regards!
