### ISSUE TITLE
Cannot run pytest for individual tests anymore

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#409]
Hi!

Since the last update, which adds Odoo run configurations (really nice!), I cannot run single unit tests through my default unit test runner anymore (pytest). I am forced to run Odoo, and that does not run the test but just starts Odoo

![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/ca386316-6168-43c6-bc42-552136156277)

**Comment by trinhanhngoc** [comment]
Hi @Jerther, Thanks for the quick report. I will look into this issue.

**Comment by trinhanhngoc** [comment]
Hi @Jerther , The new version 2023.8.3 has been released with the fix for this issue.

**Comment by Jerther** [comment]
Excellent! I confirm the fix is working
![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/56244f45-96c6-4a13-afd9-ea83633757b2)

**Comment by trinhanhngoc** [comment]
Hi @Jerther . The new version 2023.9.0 was just released with [Odoo testing integration](https://odoo-ide.com/blog/news-1/pycharm-odoo-2023-9-21). You can open **Settings > Tools > Python Integrated Tools** and set **Default test runner** to **Autodetect (Unittest)** to try the new feature.

**Comment by Jerther** [comment]
Hi @trinhanhngoc ! That looks neat! However, I can't get it to work... When I try to run a single test, or a whole test class, I get "Test framework quit unexpectedly.

![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/cb9b41a2-2569-4325-9c52-e6e3f7868444)

Here's the first line in the console:

```/home/user/git/odoo/venv_15.0/bin/python /home/user/git/odoo/odoo-bin -c /home/user/code/openerp-server.conf --test-tags /premio_mezzanine:TestMezzanine --stop-after-init ```

Here's the warning I get in the console:

```2023-09-12 14:21:26,888 92228 WARNING odoo15_dev odoo.tests.runner: 0 failed, 0 error(s) of 0 tests when loading database 'odoo15_dev' ```

Should I create a separate issue?

**Comment by trinhanhngoc** [comment]
@Jerther , Have you installed the `premio_mezzanine` module? Anyway, the message needs to be improved when no tests are run.

**Comment by Jerther** [comment]
Yes the module is installed. In fact the same exact tests run fine if I set the default test runner back to pytest.

I'll see if I can get more details when the message is improved.

**Comment by msjtheriault** [comment]
Hi, @Jerther here. I fixed the issue of Odoo as test runner not finding any test.

When using pytest, I can keep the `tests/__init__.py` file empty. But when using Odoo as test runner, [every test file has to be imported in there](https://www.odoo.com/documentation/18.0/fr/developer/reference/backend/testing.html).

**Comment by trinhanhngoc** [comment]
Hi @msjtheriault, and @Jerther =))

Nice. Are you still having the problem with the test runner setting (https://github.com/odoo-ide/pycharm-odoo/issues/513) ?
