### ISSUE TITLE
XML Data files - cmd click not working, no autocomplete

### ISSUE THREAD

**Issue by fotisp** [trinhanhngoc/pycharm-odoo#410]
Hello, 

IntelliJ
```
IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023
```

Odoo Python
```
2023.8.3.321
```

Since the last upgrade, XML files are not being considered in the Odoo context, causing previous features to stop working like:

1) CMD-Click for inherit_id ref
2) Autocomplete for model names
3) CMD-Click for widget types

etc.

These used to work on most of my projects. XML files are associated as "XML" so I don't know where to start tweaking for a solution.

I am at your disposal for any further debugging

**Comment by trinhanhngoc** [comment]
Hello @fotisp . I just checked again. Everything is still working fine. Can you check again with other XML files in the Odoo source code, e.g. `addons/sale/views/account_views.xml`?

<img width="1006" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/f7e17cbb-ad06-47e2-93e2-cfe2eb52b21f">

**Comment by fotisp** [comment]
Hello @trinhanhngoc ,

Thank you for coming back to me. Apologies for the spam, It seems to be project specific, I don't know if it is **version** specific, I need to dig a bit more into this.

An old project which I tested works just fine. I can't seem to put my finger on the reason it is not working, besides the Odoo version, the rest of the structure is quite similar between the working and non-working project.

**Comment by trinhanhngoc** [comment]
Hi @fotisp , do you still have this problem?
