### ISSUE TITLE
Support remove group syntax for menuitem groups

### ISSUE THREAD

**Issue by fanthos** [trinhanhngoc/pycharm-odoo#412]
According to `odoo.tools.convert.xml_import._tag_menuitem`, if a group in `menuitem` `groups` starts with `-`, the group will be unlinked after module upgrade. Odoo plugin does not remove the leading `-` for the symbol and the symbol does not resolve correctly.

**Comment by trinhanhngoc** [comment]
Hello @fanthos . Thanks for the information. I didn't know that Odoo had that feature. I will add support for that syntax in the next version.

**Comment by fanthos** [comment]
To distinct link and unlink, I think its better if unlink has a different color other than link( or other mark).

**Comment by trinhanhngoc** [comment]
Hello @fanthos , The new version 2023.9.1 has been released with support for group unlink syntax, you can update it.
