### ISSUE TITLE
odoo-stubs is not added as source folder

### ISSUE THREAD

**Issue by gabit-ch** [trinhanhngoc/pycharm-odoo#413]
Odoo is added as submodule to project and marked as source folder:
<img width="1156" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/23083166/1152a436-0240-4cff-8175-1b5f59902bb9">
But no odoo-stubs is synced and added to project.
Latest version of pycharm and odoo-ide plugin is installed.

**Comment by trinhanhngoc** [comment]
Hello @gabit-ch , Is `odoo-stubs` not added automatically even after restarting PyCharm?

**Comment by gabit-ch** [comment]
Hello @trinhanhngoc 
No, I have restarted PyCharm several times and there is no odoo-stubs visible in the project structure.

**Comment by trinhanhngoc** [comment]
@gabit-ch , Can you expand the `odoo` folder and take a screenshot again?

<img width="1156" alt="pycharm" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/bd177ab8-402b-4d93-839d-799b67820c24">

**Comment by gabit-ch** [comment]
Please find below the screenshot of the odoo folder:
<img width="679" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/23083166/c47b86dd-869a-430a-a222-cc25b429315b">

**Comment by trinhanhngoc** [comment]
@gabit-ch Can you temporarily **Unmark Source** all your custom addons folders except the odoo folder, then restart PyCharm and check again?

**Comment by gabit-ch** [comment]
@trinhanhngoc I have now unmark all other sources and restarted Pycharm, but there is still no odoo-stubs:
<img width="1158" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/23083166/213d76fc-8480-4165-b0cf-a27f517fbea6">

**Comment by gabit-ch** [comment]
Could it be a problem, that I have checked out master branch for odoo? I'm developing now for odoo 17 and this is why I use master branch. Before, I have added odoo-stubs as a submodule and used also checked out master branch. This worked perfect.

**Comment by trinhanhngoc** [comment]
@gabit-ch, I just found the cause of this problem. Please wait for the fix in the next version this week.

**Comment by trinhanhngoc** [comment]
Hi @gabit-ch , The new version 2023.9.1 has been released with the fix for this problem. You can update it and check again.

**Comment by gabit-ch** [comment]
@trinhanhngoc Many thanks for the bug fix. It works perfect!
