### ISSUE TITLE
Test feature does not trigger test window

### ISSUE THREAD

**Issue by Astyan42** [trinhanhngoc/pycharm-odoo#414]
Hi!

Good work on this module, it's really useful.
I've got a problem when trying to setup the testing feature.
When I click on a test to be triggered or an already existing testing configuration, the test window displaying which tests have bee run, ... is not displayed even though the console saying that the test went fine.
<img width="1216" alt="Capture d’écran 2023-09-27 à 00 24 28" src="https://github.com/odoo-ide/pycharm-odoo/assets/3466324/c3cc2ddb-7289-4b9a-a683-5b8a4423beb8">
Here you can see the screen when I click on a play button near the test.

<img width="1656" alt="Capture d’écran 2023-09-27 à 00 26 17" src="https://github.com/odoo-ide/pycharm-odoo/assets/3466324/e8a90c8e-293a-4df5-89b5-9a56282dff6b">
Here it is right after triggering the test configuration.

Thank  you for your help !
Kind regards

PS: I'm working on a Mac / using Odoo14

**Comment by trinhanhngoc** [comment]
Hello @Astyan42,

Can you take screenshots of your test run configurations?, e.g.:

<img width="841" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/5862e480-3fda-4358-81e7-0c9d4c2cb3dd">

**Comment by Astyan42** [comment]
Hi, 
Here you can find it attached.

<img width="841" alt="Capture d’écran 2023-09-27 à 10 21 37" src="https://github.com/odoo-ide/pycharm-odoo/assets/3466324/b5951ea7-2a8b-4af5-bd74-84bf35a11b96">


This is the args given to odoo-bin: 
`-c
/Users/Dev/OdooProject/Odoo-1/devenv/odoo-local.conf
--test-tags
/traceability_system
--database
BaseTest
--log-level
info
--log-handler
:INFO
--stop-after-init`

**Comment by trinhanhngoc** [comment]
@Astyan42 , there is no problem with your run configuration. Can you take a screenshot of your project structure?, e.g.:

<img width="1125" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/f348dcdf-aa66-4474-9b7b-462220921384">

**Comment by Astyan42** [comment]
<img width="888" alt="Capture d’écran 2023-09-27 à 11 12 39" src="https://github.com/odoo-ide/pycharm-odoo/assets/3466324/0da72a0a-a994-4459-abe4-6a4f3897706e">

**Comment by trinhanhngoc** [comment]
@Astyan42 , There is a problem with your project structure. You need to mark the `odoo` folder as `Sources`. This is important because if not, it will cause various problems, including the testing integration feature.

<img width="888" alt="270928289-0da72a0a-a994-4459-abe4-6a4f3897706e" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/2ea6f00d-dbe5-4e9a-9927-83b620d1e14f">

**Comment by Astyan42** [comment]
Great thank you for your help and the time spent !
Everything is now ok !
