### ISSUE TITLE
Support for OCA module "Extended view inheritance"

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#422]
This OCA module "[Extended view inheritance](https://github.com/OCA/server-tools/tree/15.0/base_view_inheritance_extension)" (v14, v15, v16), is used by other OCA modules such as "[OCA/sale_workflow/sale_order_product_availability_inline](https://github.com/OCA/sale-workflow/blob/15.0/sale_order_product_availability_inline/views/sale_views.xml)".

Since the plugin does not support this features:
```
<field position="attributes">
    <attribute name="context" operation="update">
        {
            "key": "value",
        }
    </attribute>
</field>
```

We get a XML false error:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/68a9630b-28a6-4329-bcdb-72103cf5708f)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2023.9.4 has been released with support for OCA module "Extended view inheritance".

**Comment by jcfernandez-890825** [comment]
Nice !!!
