### ISSUE TITLE
Unresolved external id references to records declared inside field tags

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#423]
`odoo/addons/l10n_be/data/account_tax_template_data.xml`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/f2bda340-3e25-4691-9465-02ad1d2cbd65)

But this record (Selected in blue) `tax_report_line_03_tag` does exist here:
`odoo/addons/l10n_be/data/account_tax_report_data.xml`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/8cfeebb8-d23c-4152-8ae0-b6a2cd3ffc0e)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 . Thank you very much! I didn't know that Odoo supports declaring records inside `field` tags. I will soon add support for this feature.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2023.9.4 has been released with support for nested record definitions.

**Comment by jcfernandez-890825** [comment]
Awesome, this will help me a lot.
Thanks, you rock, as usual.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 

A thing that I spotted after upgrading, if you do `Ctrl+Click` on `tax_report_line_03_tag` definition you get `No usages found in Project Files`:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/6bf5d53b-8ec8-4ae3-ae04-bdaa4da7b89f)

However this works the other way around:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/0c591561-9b7b-4390-adc4-b395aad36847)

if you do `Ctrl+Click` on `ref('tax_report_line_03_tag')`, you will get sent back to its definition, as it should.

Can the 1st be fixed?

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

This bug is already on my to-do list to fix soon! A workaround is to press Ctrl+Click at the start of the tag instead of at the id attribute value, e.g: `<cursor><record id="..."`
