### ISSUE TITLE
Module name autocomplete in commit message

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#424]
Hi!

I remember this was implemented not long ago, but was quickly replaced by commit history autocomplete. By that I mean this:

1- In a commit message, start writing a module name
2- Hit ctrl+space to bring up autocomplete suggestions

Expected:
- A list of modules matching the current word

Actual:
- A list of past commit messages, basically what the clock button (Ctrl+M) already does.

Now I'm aware some improvements have been made around the commit message regarding tags which I do use but don't seem to work. But I may just have lost the thread here...

**Comment by trinhanhngoc** [comment]
Hi @Jerther ,

Thank you for the information. I just tested again. There seems to be some change in PyCharm that causes this problem. I will try to fix it for the next release this week.

**Comment by trinhanhngoc** [comment]
Hi @Jerther  ,

The new version 2023.9.4 has been released with the improvement for module name autocomplete in commit message.
