### ISSUE TITLE
Go to references from XML record definition

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#425]
@trinhanhngoc 

A thing that I spotted after upgrading, if you do `Ctrl+Click` on `tax_report_line_03_tag` definition you get `No usages found in Project Files`:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/6bf5d53b-8ec8-4ae3-ae04-bdaa4da7b89f)

However this works the other way around:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/0c591561-9b7b-4390-adc4-b395aad36847)

if you do `Ctrl+Click` on `ref('tax_report_line_03_tag')`, you will get sent back to its definition, as it should.

Can the 1st be fixed?

_Originally posted by @jcfernandez-890825 in https://github.com/odoo-ide/pycharm-odoo/issues/423#issuecomment-1780686265_

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825,

The new version 2023.9.5 has been released with the fix for this issue.

**Comment by jcfernandez-890825** [comment]
Nice, I will upgrade the plugin and check it out. As usual, outstanding work.

👏👏👏
