### ISSUE TITLE
Latest version brakes all tests based on unittest.TestCase 

### ISSUE THREAD

**Issue by selcukatay** [trinhanhngoc/pycharm-odoo#429]
Latest version brakes all tests based on unittest.TestCase 
It shows run Odoo and debug odoo instead of run the test method

![image](https://github.com/odoo-ide/pycharm-odoo/assets/43198741/e1cf96c2-e54a-41ca-a795-59424238e67e)

![image](https://github.com/odoo-ide/pycharm-odoo/assets/43198741/818adc9b-c992-4e53-9946-fa315a2b2af9)

**Comment by trinhanhngoc** [comment]
Hello @selcukatay , 

I just checked again and didn't see any problems.

<img width="993" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/06b48d23-15e7-48a2-9862-ac7ceda8c583">

What version of Odoo and Odoo plugin are you using?

**Comment by selcukatay** [comment]
Plugin version is 2023.9.4.232

These test are not related to odoo, the test class is extended directly from the unittest.TestCase (not from a odoo test class)
And the problem is the plugin tries to run all tests with odoo even the **regular tests**.
What should I see is here (I just disabled the plugin to the get this screenshot)

![image](https://github.com/odoo-ide/pycharm-odoo/assets/43198741/d6492c7d-3b21-47c8-aecd-c1be55fb31bd)

**Comment by trinhanhngoc** [comment]
@selcukatay 

Thank you for the additional information. I confirm this is a bug. This bug will be fixed in the next release.

**Comment by trinhanhngoc** [comment]
Hello @selcukatay ,

The new version 2023.9.5 has been released with the fix for this bug.
