### ISSUE TITLE
Plugin tries to run all main methods with Odoo

### ISSUE THREAD

**Issue by selcukatay** [trinhanhngoc/pycharm-odoo#432]
The plugin tries to run all main methods with odoo. This is a similar issue with #429 

![image](https://github.com/odoo-ide/pycharm-odoo/assets/43198741/5e524cfa-a44f-4ab5-97c7-4652c8a8fbeb)

![image](https://github.com/odoo-ide/pycharm-odoo/assets/43198741/b6b4f3b9-bb8d-4edc-b2f3-79fdbb966bf3)

**Comment by trinhanhngoc** [comment]
Hello @selcukatay ,

Thank you for the information. I missed this case in the previous fix. This bug will be fixed in the next release this week.

**Comment by trinhanhngoc** [comment]
Hello @selcukatay,

The new version 2023.9.6 has been released with the fix for this bug.
