### ISSUE TITLE
Unresolved dot-separated field references in filtered()

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#439]
OdooEEv15

In `odoo/addons/account/models/account_move.py`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/ff864a2c-ffef-4213-8cc8-d1594ab338f6)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2023.9.11 has been released to address this issue.
