### ISSUE TITLE
Unresolved attribute reference 'session' for class 'Request' 

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#446]
`odoo/addons/hr_attendance/controllers/main.py`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/24b08239-4acc-4b74-ae02-8f371653ba08)

**Comment by trinhanhngoc** [comment]
This affects Odoo <= 15. I will address this issue in the next version.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.1.0 has been released to address this issue.
