### ISSUE TITLE
Disable the PyUnusedLocal inspection on migration functions

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#454]
On migration functions like this one:

`odoo/addons/l10n_es/upgrades/5.1/post-migrate_update_taxes.py`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/cd1500ca-bb67-45f4-9bf9-cc52aa709501)

Could you disable the PyUnusedLocal inspection ?

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 

Yes, we can disable that inspection for migration functions.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.3.0 has been released to address this issue.
