### ISSUE TITLE
Value debugging stuck at "loading values" has no preview

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#459]
Hi!!

Every now and then I come across situations where I need to debug a variable that shows no preview and is stuck at "Loading Value":

![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/8588f6aa-af31-412e-a0b6-27845652a91c)

In this example, I understand the plugin is sort of stuck in a deadlock (and I'm not questionning that) but it would be nice to have at least something like "{stock.picking: 1}" in the red rectangle rather than nothing at all.

Cheers :)

**Comment by trinhanhngoc** [comment]
@Jerther ,

I think this issue is related to https://github.com/odoo-ide/pydevd-odoo/issues/5. Please upgrade `pydevd-odoo`.

**Comment by Jerther** [comment]
Sorry I forgot to include the plugin's version: 2024.1.2.233

Eventually it shows "Loading timed out" though

![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/1442a8fc-cf6e-4654-be2f-338206fafd79)

Also, when hovering the mouse over the variable, nothing pops up. This is no big deal in short methods, but sometimes I have to scroll all around to find the variable.

**Comment by Jerther** [comment]
Alright this is fixed in pydevd-odoo 1.2.2, thanks!!!
