### ISSUE TITLE
Debugging an Odoo model variable causes "TypeError: get_str() takes 2 positional arguments but 3 were given"

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#460]
Hello!

I can no longer debug Odoo model variables in the debugger's "Variables" tab:

![image](https://github.com/odoo-ide/pycharm-odoo/assets/5856745/c66c7572-b686-4ee1-b7b0-c1d6103b0474)

I get around that by writing "picking.read()" or "str(picking)". Not ideal though.

**Comment by trinhanhngoc** [comment]
Hello @Jerther ,

The same issue was reported at https://github.com/odoo-ide/pydevd-odoo/issues/5 and fixed. Please upgrade `pydevd-odoo`.

**Comment by Jerther** [comment]
Sorry I forgot to include the plugin's version :sweat_smile:
2024.1.2.233

**Comment by trinhanhngoc** [comment]
> Sorry I forgot to include the plugin's version 😅 2024.1.2.233

@Jerther , The issue is actually at `pydevd-odoo`. You need to upgrade `pydevd-odoo`.

https://github.com/odoo-ide/pydevd-odoo/issues/5.

**Comment by Jerther** [comment]
Oh sorry! My bad :) Let me try.

**Comment by Jerther** [comment]
I was using 1.2.1, that's indeed fixed in 1.2.2! Thanks and sorry :sweat_smile:
