### ISSUE TITLE
Take in account selection_add

### ISSUE THREAD

**Issue by odoo-siqual** [trinhanhngoc/pycharm-odoo#462]
When I add elements to my state with selection_add, I still see an error for those elements when I use them in other parts of the code.

**Comment by trinhanhngoc** [comment]
Hello @odoo-siqual ,

Can you provide screenshots of your problem?

**Comment by odoo-siqual** [comment]
![usage of selection_add](https://github.com/odoo-ide/pycharm-odoo/assets/60179098/ba74b546-7fd6-4f4c-80ae-4cb6fdb2c098)
![error for element](https://github.com/odoo-ide/pycharm-odoo/assets/60179098/83a9c2f8-8f11-439d-b450-ac1aa9727d12)

**Comment by trinhanhngoc** [comment]
@odoo-siqual , what Odoo plugin version are you using?

**Comment by odoo-siqual** [comment]
2024.2.0.233

**Comment by trinhanhngoc** [comment]
Thank you for the information. I think I found the cause of the problem. A workaround is not using the translation function for selection labels. e.g.: `_('Lost')` => `'Lost'`. I will address this issue in the next version.

**Comment by odoo-siqual** [comment]
Thank you.
