### ISSUE TITLE
Improved cursor position after auto complete interferes with live template completion

### ISSUE THREAD

**Issue by ThomasDePontieuSomko** [trinhanhngoc/pycharm-odoo#463]
The "Improved cursor position after selecting model name, field name,... completion items" in 2024.2.0 causes live templates to be interrupted by exiting the dynamic template variable completion.

For example, this template to create a Many2one field ends immediately after auto-completing the model name, instead of jumping to the next dynamic variable.

![auto_complete_cursor](https://github.com/odoo-ide/pycharm-odoo/assets/128370705/e8a2733a-23a4-4eea-aacf-234fa61f4945)

**Comment by trinhanhngoc** [comment]
Hello @ThomasDePontieuSomko ,

I could not reproduce the problem. Here is my screencast:

https://github.com/odoo-ide/pycharm-odoo/assets/11208291/d1b12660-c124-453d-8611-b0c662d5b67c

**Comment by ThomasDePontieuSomko** [comment]
Hi @trinhanhngoc ,

I've done some more testing and it seems that the problem only occurs when the next dynamic value in the template is positioned **before** the one completed by the odoo plugin. So for example:

Templates that have the issue:
```python
$VAR_2$ = fields.Many2one('$VAR_1$', string='$VAR_3$')
``` 

Templates that  don't have the issue:
```python
field_name = fields.Many2one('$VAR_1$', string='$VAR_2$')
$VAR_3$ = fields.Many2one('$VAR_1$', string='$VAR_2$')
``` 

Where the templates cycles through the dynamic variables in the following order VAR_1 > VAR_2 > VAR_3

**Comment by trinhanhngoc** [comment]
Hi @ThomasDePontieuSomko ,

Thank you for the additional information. I confirm the issue. This issue will be addressed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @ThomasDePontieuSomko ,

The new version 2024.2.1 has been released with the fix for this issue.
