### ISSUE TITLE
Issues with upgrade tools

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#466]
I know `openupgrade` from `openupgradelib`  is the to-go tool/package when coding migrations (`pre-*.py` and/or `post-*.py`).

```
venv/bin/pip install -c src/odoo/requirements.txt --upgrade git+https://github.com/OCA/openupgradelib.git@master
```

But recently I found this in-house tool made by Odoo:
https://www.odoo.com/documentation/17.0/developer/reference/upgrade_utils.html

Which I installed using the same approach as OCA `openupgradelib`:

```
venv/bin/pip install -c src/odoo/requirements.txt --upgrade git+https://github.com/odoo/upgrade-util@master
```

The problem:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/466d0d78-5e8e-4566-a8f5-e0a650c0defc)

![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/a0649a2b-29b5-499d-8c44-0190b149b259)

This is the relative to project path `./odoo16e/local/payment_valitorpay/migrations/16.0.1.0.0/pre-migration.py`

This is my project structure:
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/9bfc51c7-1986-408d-9c7e-fd243b7a5a2a)

When I navigate into `odoo.upgrade`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/b6ab02e6-3623-4c84-b300-24286847178c)

I end up in `./odoo16e/src/odoo/odoo/upgrade/__init__.py`

Is there a way to fix this?

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

I just checked this case. I think PyCharm cannot handle this case by default. I will add a custom import resolution for this case in the Odoo IDE plugin. Stay tuned.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.3.0 has been released to address this issue. Happy coding!!!
