### ISSUE TITLE
Not compatible Gateway 2023.3.4, PyCharm 2024.1 EAP

### ISSUE THREAD

**Issue by theandryx** [trinhanhngoc/pycharm-odoo#467]
Is there date for a plugin update that will make this version compatible? Thanks

**Comment by trinhanhngoc** [comment]
Hello @theandryx ,

The latest Odoo plugin version (2024.2.2) is already compatible with PyCharm 2024.1 EAP.

**Comment by theandryx** [comment]
I'm trying to install it, but from the marketplace on the remote I can't find the application.
And from the website with pycharm opened i've this alert
<img width="1396" alt="Screenshot at Mar 26 09-22-45" src="https://github.com/odoo-ide/pycharm-odoo/assets/8146730/da66f5ac-b9db-46b5-a877-ade03c0b456b">

**Comment by trinhanhngoc** [comment]
Have you tried installing the plugin from the PyCharm Settings?

Here is my PyCharm 2024.1 RC:
<img width="1094" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/db9d7cd6-2abd-4eeb-988e-e24f11df33e8">

**Comment by theandryx** [comment]
Yes, i've searched inside it but from the remote instance there isn't the plugin, only odoo autocompletion.
I haven't said that i'm using the remote SSH version of pycharm.
From the screen in the host ( my mac ) is installed, but the client ( my server ) hasn't it in the marketplace list 
<img width="1001" alt="Screenshot at Mar 26 10-56-42" src="https://github.com/odoo-ide/pycharm-odoo/assets/8146730/eb21a384-abd1-4af9-a645-b26bbdb17144">

**Comment by trinhanhngoc** [comment]
@theandryx There is no problem here. Installing the Odoo plugin on the host (the host is your server, the client is your mac) is enough to get the plugin working as expected for projects on the remote host.

<img width="1094" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/39832f8b-f5d9-4f19-81d6-fdf87550e8dc">
<img width="1094" alt="image" src="https://github.com/odoo-ide/pycharm-odoo/assets/11208291/986cca69-eb3c-41e5-9d34-543cceb31293">

**Comment by theandryx** [comment]
Ok, I've tried to make it appear in the list, sorry , maybe it's still loading my working directory because trying it doesn't seem to work, I will wait some time to check if it start working.
In the meantime thanks a lot
