### ISSUE TITLE
Disable the PyUnusedLocal inspection on hook functions

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#468]
On hook functions like this ones:

`odoo/addons/l10n_mx_edi_extended/hooks.py`

`odoo/addons/product_unspsc/hooks.py`

`odoo/addons/l10n_mx_edi/hooks.py`
![image](https://github.com/odoo-ide/pycharm-odoo/assets/28876647/f5302205-a20a-4652-9e1c-656a50df2f0d)

Could you disable the PyUnusedLocal inspection ?

So pretty much on any function mentioned in the [...hook] keys inside the `__manifest__.py`

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

👌👌👌👌👌👌👌👌👌👌

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.3.2 has been released with this improvement.
