### ISSUE TITLE
Code in "base.automation" does not automatically prompt like in "ir.server.actions"

### ISSUE THREAD

**Issue by NqanVo** [trinhanhngoc/pycharm-odoo#479]
![Ảnh chụp màn hình (2122)](https://github.com/user-attachments/assets/8b7176ef-d2de-4d3e-aacb-c4201a94fb5e)
![Ảnh chụp màn hình (2123)](https://github.com/user-attachments/assets/5ffed46b-f7bc-496a-bc88-2e9fa66e70f6)

And when formatting code it automatically indents lines equally

![Ảnh chụp màn hình (2124)](https://github.com/user-attachments/assets/8f91a5e1-9950-4cd0-a3b6-1f6aba8857d9)
![Ảnh chụp màn hình (2125)](https://github.com/user-attachments/assets/d1689488-6eeb-45e2-b796-a0c8182f5fde)

**Comment by trinhanhngoc** [comment]
Hello @NqanVo ,

Thanks for the information. I will improve it in the next version.

**Comment by trinhanhngoc** [comment]
Hello @NqanVo ,

The new version 2024.7.0 has been released with support for `base.automation` records.
