### ISSUE TITLE
Corresponding type hint is not returned

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#48]
When using a variable (`model = 'sale.order'`) for Environment (`self.env[model]`), returned type hint is BaseModel.
![image](https://user-images.githubusercontent.com/28876647/145291924-f434b491-d288-4592-9e4f-291250860097.png)

![image](https://user-images.githubusercontent.com/28876647/145292045-de9a95e0-28cb-4960-be44-6cf442b48931.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

This issue has just been fixed. Please wait for the fix in the next version. Thanks.
