### ISSUE TITLE
Cannot find reference on "self.env.user"

### ISSUE THREAD

**Issue by V3st1g3** [trinhanhngoc/pycharm-odoo#487]
It seems whatever attribute I attempt to get from "self.env.user" is treated as a function.

![Screenshot_20240912_152234](https://github.com/user-attachments/assets/2314f292-5e89-40b2-a1cb-22393e75de1b)

**Comment by trinhanhngoc** [comment]
Hello @V3st1g3 ,

What version of PyCharm and Odoo plugin are you using?

**Comment by V3st1g3** [comment]
I am using PyCharm 2024.2.1 and Odoo plugin 2024.7.0.242.

**Comment by trinhanhngoc** [comment]
@V3st1g3 ,

Your problem is strange. I just tested and could not reproduce the problem.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/51371514-f549-4d0b-ad28-08c2434ad026">

Can you take a screenshot of the code completion for `res.users` members after typing `self.env.user.` ?

**Comment by V3st1g3** [comment]
This is what I get.

![Screenshot_20240912_172240](https://github.com/user-attachments/assets/036d29dc-9c7f-4010-88c8-3069e1a67c25)

**Comment by trinhanhngoc** [comment]
@V3st1g3 , 

Have you tried navigating to the definitions of `env` and `user` in `self.env.user`? Where are the destinations?

**Comment by V3st1g3** [comment]
For "env", I get "Cannot find declaration to go to".
For "user", it goes to "api.py".

![Screenshot_20240912_175015](https://github.com/user-attachments/assets/16ced94f-0b49-4ab8-8dac-e2bb5bfc5069)

**Comment by trinhanhngoc** [comment]
@V3st1g3 ,

How does your project structure look? This is my project structure:

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/0364e741-c2d1-4cfb-a281-ccb4d0d1bbb6">

**Comment by V3st1g3** [comment]
It's quite the same except for "odoo-stubs".
Should I try to add it ?

**Comment by V3st1g3** [comment]
OK, now it works with "odoo-stubs" added.
Sorry for wasting your time. 🙏

**Comment by trinhanhngoc** [comment]
@V3st1g3 ,

The Odoo plugin will attach `odoo-stubs` automatically unless it cannot detect your Odoo version.

**Comment by V3st1g3** [comment]
Indeed, I never needed to do it manually.
I am using a remote interpreter from a Docker image like I always did.
In the case it cannot detect my Odoo version, is there a way to "tell" it?

**Comment by trinhanhngoc** [comment]
@V3st1g3 ,

Currently there is no manually way to tell it. If the Odoo source code directory (contains `odoo-bin`) is not the root directory in the project structure, then you need to mark it as `Sources` in the Project Structure setting, so the Odoo plugin can discover it:

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/33e95336-b231-4b76-8709-455ee65448bf">
