### ISSUE TITLE
XML tag error in PyCharm

### ISSUE THREAD

**Issue by aqeebimtiaz** [trinhanhngoc/pycharm-odoo#49]
Facing this issue after updating PyCharm & Odoo plugin for the last 2 days, even in Odoo 14 base files. `field`, `kanban`, `templates`, etc. is marked as error. 
I have tried enabling only Odoo plugin & disabling all other plugins, as well as invalidating caches & restarting. Also, the plugin is crashing every 30-40 minutes. I'll try to add the error log that pops up.

![Screenshot from 2021-12-21 15-50-37](https://user-images.githubusercontent.com/17214391/146910628-c587d140-f348-45a2-a9be-9b32cafd8243.png)

Any solution on this?

**Comment by trinhanhngoc** [comment]
Hi @aqeebimtiaz ,

This seems be a bug related to view inheritance. While waiting for the fix, you can try installing XPathView (https://plugins.jetbrains.com/plugin/12478-xpathview--xslt) as recommended to see if it helps. Thank you the reporting.

**Comment by aqeebimtiaz** [comment]
Hi, @trinhanhngoc! Thank you for the quick reply! :) 

I've already added the XPathView plugin, seems to solve some of the errors in the custom modules. But there are still some errors like these in the base files.

**Comment by trinhanhngoc** [comment]
@aqeebimtiaz This is strange. Everything is ok on my machine.

![Screenshot from 2021-12-22 18-41-12](https://user-images.githubusercontent.com/11208291/147087642-a1f4a14d-c991-45b4-ae53-e5ab67fb55cd.png)

**Comment by daemonblade** [comment]
I can confirm that this bug is happening with the latest update to 2021.12.1
![pycharm-odoo](https://user-images.githubusercontent.com/1181569/147152805-bca284b1-ac58-4c3b-bebe-954bcfe8263d.png)

**Comment by trinhanhngoc** [comment]
> I can confirm that this bug is happening with the latest update to 2021.12.1 ![pycharm-odoo](https://user-images.githubusercontent.com/1181569/147152805-bca284b1-ac58-4c3b-bebe-954bcfe8263d.png)

Yes, this is a bug. Anyway, I recommend you to install XPathView (https://plugins.jetbrains.com/plugin/12478-xpathview--xslt) to enable features related to view inheritance.

**Comment by trinhanhngoc** [comment]
Hi all, the new version 2021.12.2 has just been released with the fix for this issue, please update the plugin.

**Comment by aqeebimtiaz** [comment]
@trinhanhngoc Sorry for the late reply, issue resolved on my end as well! Thanks!
