### ISSUE TITLE
Navigate to relative filepath

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#490]
This function from v17 `file_path`, it would be nice that Odoo could navigate to the file and show an error is the path is incorrect.

`odoo/addons/l10n_be_hr_payroll/models/l10n_be_281_45.py`
![image](https://github.com/user-attachments/assets/05624f0d-f8a2-42dd-a23e-0c9cf463fd88)

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

Nice feature request! I will add this feature to the next release.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.8.0 has been released with support for file_path().
