### ISSUE TITLE
Unresolved reference 'self'

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#491]
`src/odoo/odoo/models.py`
![image](https://github.com/user-attachments/assets/e9f6db6a-3242-4e8a-b635-03ead3e0581b)

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

Thanks for the report. This will be fixed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.8.0 has been released with the fix.
