### ISSUE TITLE
Navigate JS import

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#492]
The plugin supports navigation in JS imports when it has the format

`import core from 'web.core';`

But it does not allow navigation when is like this

`import "core";`

`odoo/addons/web_editor/static/src/js/backend/field_html.js`

![image](https://github.com/user-attachments/assets/ee0b05a2-1e24-42dc-bb37-ed0bcf947c05)

![image](https://github.com/user-attachments/assets/6c661f15-2964-4df3-8119-b78ad962a8e5)

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 

Unbelievable! This must be fixed in the next version. Thanks for the report.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.8.0 has been released to address this problem.
