### ISSUE TITLE
XML navigation is not working

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#494]
Tried in v16 and v17
Filepath `odoo/addons/payment_adyen/data/payment_provider_data.xml`

When clicking the name ...
![image](https://github.com/user-attachments/assets/627d3a21-966a-4cb2-a20f-e39c2272fc0b)

When clicking the `<` ...
![image](https://github.com/user-attachments/assets/18514160-7828-4aed-aaab-88abf6fdd7d8)

Same thing happens in the main XML definition
Filepath `odoo/addons/payment/data/payment_provider_data.xml`

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

I just fixed this issue. Please wait for the new version this week.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version 2024.8.0 has been released to address this problem.
