### ISSUE TITLE
Support running tests with pytest

### ISSUE THREAD

**Issue by seletz** [trinhanhngoc/pycharm-odoo#496]
I use *pytest* with the `pytest-odoo` plugin for fast unit and integration tests.  This works nicely when I add a pytest based run configuration.

However, when I click on the "run test" button:

![image](https://github.com/user-attachments/assets/5648d31a-9cfe-4619-a6a7-f70c83b49d45)

A Run Configuration template from the ODOO Plugin is used:

![image](https://github.com/user-attachments/assets/57e1f1f5-cdc3-42a8-897d-c1a358df8e63)

It would be nice if we could tell the Plugin to use a different Run Configuration Template, or if the ODOO Plugin yould directly support `pytest`.

**Comment by trinhanhngoc** [comment]
Hello @seletz ,

Have you set the **Default test runner** setting to pytest?

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/13f32608-7c63-44f7-80d1-7b9598894ee1">

**Comment by seletz** [comment]
@trinhanhngoc  IntelliJ auto-detects `pytest`.  I changed it from `Autodetect` to `pytest` just to try it out, but that did not change the behaviour.

**Comment by trinhanhngoc** [comment]
Hello @seletz ,

Thanks! I just reproduced the issue. Please wait for the new version with the fix next week.

**Comment by seletz** [comment]
@trinhanhngoc 👍

**Comment by trinhanhngoc** [comment]
@seletz ,

What version of PyCharm are you using?

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc IntelliJ auto-detects `pytest`. I changed it from `Autodetect` to `pytest` just to try it out, but that did not change the behaviour.

I tested with PyCharm 2024.2.3. After I change the setting to `pytest`, PyCharm uses the Python test configuration template instead of the Odoo configuration template.

**Comment by seletz** [comment]
> @seletz ,
> 
> What version of PyCharm are you using?

I use IntelliJ Ultimate 2024.2.3

**Comment by seletz** [comment]
> > @trinhanhngoc IntelliJ auto-detects `pytest`. I changed it from `Autodetect` to `pytest` just to try it out, but that did not change the behaviour.
> 
> I tested with PyCharm 2024.2.3. After I change the setting to `pytest`, PyCharm uses the Python test configuration template instead of the Odoo configuration template.

Yes -- I see.  Sorry, I don't know where I was looking when I tested that.  Indeed it uses the `pytest` template.

**Comment by trinhanhngoc** [comment]
Hello @seletz ,

The new version 2024.8.1 has been released with the improvement for pytest detection. You can switch the default test runner setting to the default value (Autodetect).

**Comment by Jerther** [comment]
Hi @trinhanhngoc 

I'm having the same problem...

Pycharm 2024.3
pycharm-odoo 2024.9.3.243

The run menu always shows Run Odoo tests, no matter what I set the default runner to.

![image](https://github.com/user-attachments/assets/bdba748d-a760-438c-8cba-e08a8a45e86e)

![image](https://github.com/user-attachments/assets/af41c4c5-497c-49a9-ae3f-dd08bb43e65f)

It's fine in the unit test window though:

![image](https://github.com/user-attachments/assets/38663aad-0f0b-4997-a7fb-8f93c7d5b2d8)
