### ISSUE TITLE
Display SubTest as fail

### ISSUE THREAD

**Issue by chmuche** [trinhanhngoc/pycharm-odoo#511]
Hello, 
This is an awesome plugin, and the new Run Debug for Odoo is very nice.

I have a weird bug when I run a subtest 
For example,

```python
@tagged('subtest')
class SubTestFailSuccess(TransactionCase):

    def test_01(self):
        with self.subTest("My subtest"):
            self.fail("FAIL")


    def test_02(self):
       # Fail is ok for this one
        with self.with_user('demo'):
            self.fail("FAIL")

    @users('demo', '__system__')
    def test_03(self):
        self.fail("FAIL")

    def test_assertQueryCount(self):
        with self.assertQueryCount(0):
            self.env['res.partner'].search([])
```
When I run this Case I get this result in the `Run` pane

![image](https://github.com/user-attachments/assets/78480aae-189f-4e83-9106-af490f47f12a)

It's only when I use `subTest` and the subtest Failed

. `assertQueryCount` and `@users` internally use a `subtest`

**Comment by trinhanhngoc** [comment]
Hello @chmuche ,

What Odoo version are you using?

**Comment by chmuche** [comment]
Odoo 15.0 and Version 16.0
Plugin version : 2024.8.0.242

**Comment by chmuche** [comment]
Same error with the Plugin in version `2024.9.1.243`

**Comment by trinhanhngoc** [comment]
@chmuche ,

Thanks for the report. This issue will be addressed in the next version.

**Comment by trinhanhngoc** [comment]
Hello @chmuche ,

The new version 2024.9.3 has been released with the fix for this issue.
