### ISSUE TITLE
Odoo plugin does not respect test runner setting in PyCharm 2024.3

### ISSUE THREAD

**Issue by trinhanhngoc** [trinhanhngoc/pycharm-odoo#513]
Hi @trinhanhngoc 

I'm having the same problem...

Pycharm 2024.3
pycharm-odoo 2024.9.3.243

The run menu always shows Run Odoo tests, no matter what I set the default runner to.

![image](https://github.com/user-attachments/assets/bdba748d-a760-438c-8cba-e08a8a45e86e)

![image](https://github.com/user-attachments/assets/af41c4c5-497c-49a9-ae3f-dd08bb43e65f)

It's fine in the unit test window though:

![image](https://github.com/user-attachments/assets/38663aad-0f0b-4997-a7fb-8f93c7d5b2d8)

_Originally posted by @Jerther in https://github.com/odoo-ide/pycharm-odoo/issues/496#issuecomment-2491997764_

**Comment by trinhanhngoc** [comment]
Hi @Jerther,

I just reproduced the issue. It seems like there is some change in PyCharm 2024.3 that causes this issue. Thanks for the report. This will be fixed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @Jerther,

The new version 2024.9.4 has been released with the fix for test runner.

**Comment by msjtheriault** [comment]
Hi @trinhanhngoc 

Nothing's changed on my end :(

Odoo plugin 2024.9.4.243
Pycharm 2024.3 community

![image](https://github.com/user-attachments/assets/7638bff2-e9d9-4c14-b339-bf8ffe701807)

![image](https://github.com/user-attachments/assets/ee2dd8ae-62da-4161-9144-119c89966f18)

Also, I'm not sure if this is related, but I cannot run pytest from the context menu of the project pane either:

![image](https://github.com/user-attachments/assets/46a90daf-3940-4cfa-b606-05821083bd7e)

**Comment by trinhanhngoc** [comment]
Hi @msjtheriault ,

What Odoo version are you working on?

**Comment by msjtheriault** [comment]
Odoo 17.0

(I'm @Jerther. I had to create another account with a corporate email. I hope this is not confusing.)

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

I just tested with PyCharm Community 2024.3 + Odoo 17 and it's working for me.

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/cca4510f-c682-47f5-8a68-b2f6f0862c90">

Have you restarted PyCharm after updating the Odoo plugin?

**Comment by msjtheriault** [comment]
Yes I did. Hmmm, let me look further. My PyCharm config has been rolling on for years. Might be something wrong in there.

**Comment by msjtheriault** [comment]
I have deleted the `.idea` folder for my project and restarter pycharm. Now it's fine in the project pane context menu, but I'm still stuck with Odoo in the test menu:

![image](https://github.com/user-attachments/assets/03e04b10-e944-4ab8-8007-23af87cad02a)

![image](https://github.com/user-attachments/assets/c8f4c40c-5663-4227-81e0-b8fd3a37d6cf)

I have no Idea where else to look. Any idea?

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

Are you using PyCharm on Linux?

**Comment by msjtheriault** [comment]
Yes, Fedora Linux.

My coworker has a clean install of Pycharm and the plugin on Ubuntu, and he does not have this problem.

**Comment by msjtheriault** [comment]
I cleared all the cache using Pycharm's feature

![image](https://github.com/user-attachments/assets/374e4937-01dc-43b9-9d10-2c1b87b44c9d)

Upon restarting, the test context menu showed the pytest options while pycharm did some "scanning" and "Indexing"

![image](https://github.com/user-attachments/assets/20c9640b-c45d-4533-bf8d-73835d7bbc29)

But after that, the "Odoo Test" options were back

![image](https://github.com/user-attachments/assets/0385212d-8f6a-4980-a6a1-8b77c67dc89f)

I'm still looking...

**Comment by msjtheriault** [comment]
@trinhanhngoc Well after further looking with my coworker, he has the same problem on his installation. We can't get rid of "Odoo Tests" in individual tests context menu.

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

Have you tested with tests in the Odoo source code? Do they have the same problem?

**Comment by msjtheriault** [comment]
Yes. The tests in odoo/addons show the same behavior: _pytest_ is available while pycharm is scanning and indexing, then _Odoo Test_ takes over.

![image](https://github.com/user-attachments/assets/9426a4e2-a2c2-43e9-9b43-38fad9fc4450)


![image](https://github.com/user-attachments/assets/63e32529-ab15-4f26-8800-bb4c35477c3b)

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

Can you give me a screenshot of Type Hierarchy (in Navigate menu) of the class `TestAccountPayment`?:

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/6af18fab-afbd-41f6-8bf3-7b85e8a3b610">

**Comment by msjtheriault** [comment]
Yours looks different than mine. Note that I'm using Odoo 17.0.

![image](https://github.com/user-attachments/assets/a6ace258-58e3-4884-a3d4-5f3131846999)

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

I just created a temporary version of the Odoo plugin to try fixing your problem. You can test it to see if it works:

[pycharm-odoo-2024.9.5.243.zip](https://github.com/user-attachments/files/17936923/pycharm-odoo-2024.9.5.243.zip)

**Comment by msjtheriault** [comment]
Yes it does!! :smiley: 

![image](https://github.com/user-attachments/assets/7de299b7-75cc-40cf-a30c-1d34787c714f)

**Comment by trinhanhngoc** [comment]
Wow, you can try switching the default test runner setting to other options to verify if the setting is respected by the plugin. If ok, I will add the fix to the next version.

**Comment by msjtheriault** [comment]
| Default test runner | individual test menu |
|---|---|
| Autodetect | pytest |
| pytest | pytest |
| Unittests | Odoo Tests |

Not sure if that last one is intended or not...

**Comment by trinhanhngoc** [comment]
@msjtheriault ,

Thanks for the report. The last one is intended. I will add the fix to the new version 2024.9.6 this week.

**Comment by trinhanhngoc** [comment]
@msjtheriault , @Jerther,

I’ve created a new version with a different fix for your problem. Can you help me check if it also works for you?

[pycharm-odoo-2024.9.5.243.zip](https://github.com/user-attachments/files/17945348/pycharm-odoo-2024.9.5.243.zip)

**Comment by msjtheriault** [comment]
@trinhanhngoc , Yep, it's fine. Although I can't tell with certainty that the plugin is up to date because the versions are the same. But I did install the last file, and restarted the IDE.

**Comment by msjtheriault** [comment]
@trinhanhngoc Well this morning this version https://github.com/odoo-ide/pycharm-odoo/issues/513#issuecomment-2505592215 stopped working for some reason. I had to revert to the previous one in https://github.com/odoo-ide/pycharm-odoo/issues/513#issuecomment-2504219590 and it's working again.

**Comment by trinhanhngoc** [comment]
@msjtheriault @Jerther Thanks for the info.

**Comment by msjtheriault** [comment]
@trinhanhngoc I just updated to `2024.9.6.243` and it's fine! Thanks!
