### ISSUE TITLE
Unresolve widget references in PyCharm Community

### ISSUE THREAD

**Issue by piruin** [trinhanhngoc/pycharm-odoo#514]
Can't resolve widget references
![image](https://github.com/user-attachments/assets/26aab29c-a9a1-4cc7-8876-b64d18abf787)

![image](https://github.com/user-attachments/assets/edae71c8-e08d-445c-b25b-f8088a4dc71d)

Odoo plug-in version `2024.9.4.243`
PyCharm 2024.3 Build #PC `243.21565.199`

**Comment by trinhanhngoc** [comment]
Hello @piruin ,

I just tested and confirmed the bug. This bug will be fixed in the next version. Thanks for the report.

**Comment by trinhanhngoc** [comment]
Hello @piruin ,

The new version 2024.9.5 has been released with the fix.
