### ISSUE TITLE
Widget not shown automatically

### ISSUE THREAD

**Issue by hra0123** [trinhanhngoc/pycharm-odoo#515]
I am using latest odoo plug in version 2024.9.4.242 and PyCharm 2024.2.4 (Community Edition)
In previous version widget are working fine , 
now widget option in red . widget not autofilled . I am typing then need to type full widget like 
widget="many2many_tags", widget="float" etc . 
i checked in base and custom modules , all widgets in red . 
![Screenshot from 2024-11-27 14-48-56](https://github.com/user-attachments/assets/85b30341-aa9f-4f85-b0bc-b86828d22c25)

**Comment by trinhanhngoc** [comment]
Hello @hra0123 ,

Your issue duplicates https://github.com/odoo-ide/pycharm-odoo/issues/514. Please wait for the fix in the next version this week.

**Comment by trinhanhngoc** [comment]
Hello @hra0123 ,

The new version 2024.9.5 has been released with the fix.
