### ISSUE TITLE
Navigation for context flags

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#516]
Odoo plugins offers navigation for context data, however, it does not seems to be always working for the method `with_context`, for example, here `odoo/addons/l10n_ec_edi/models/account_tax.py` in the `compute_all` method:
![image](https://github.com/user-attachments/assets/b96cb7d6-9835-4600-9290-b6cf3e3cce7d)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

Thanks for the report. This will be addressed in the next version.

**Comment by trinhanhngoc** [comment]
Hello @jcfernandez-890825 ,

The new version 2024.9.6 has been released to addess this issue.
