### ISSUE TITLE
Warning - Unexpected type(s)

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#523]
I'm getting the following warning `Unexpected type(s):(() -> bool, str)Possible type(s):(None, Iterable[str | None])((_S) -> TypeGuard[_T], Iterable[str])((_T) -> Any, Iterable[str])` for this code:
![image](https://github.com/user-attachments/assets/b97fa7a5-626b-43c6-b671-0e5c59294540)

Is there a way to silence this?

**Comment by trinhanhngoc** [comment]
Hello @jcfernandez-890825 , this duplicates your previous issue #485. This is a PyCharm bug. I will look into this to see if there is something I can do.
