### ISSUE TITLE
Name auto-completion and jump to source with "CTRL+Right-Click" for "report_name" and "report_file" in Report Actions (ir.actions.report)

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#56]
![image](https://user-images.githubusercontent.com/28876647/148124473-a5a79a93-1705-44b3-82ba-acbf383dd7a7.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

It seems that only `report_name` is a XML ID. This improvement has just been implemented and will be available in the next version. Thanks.
