### ISSUE TITLE
"Redundant default attribute value assignment " warning in XML

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#57]
![image](https://user-images.githubusercontent.com/28876647/148125550-86e8eea8-d9fc-459b-a578-6770cf636808.png)

**Comment by ghost** [comment]
Hi @jcfernandez-890825 ,

What plugin version are you using? On my machine, there is no this issue.

![Screenshot from 2022-01-06 20-59-38](https://user-images.githubusercontent.com/65052910/148394482-05ef247f-550e-425c-97ad-36ac949f9b0e.png)

**Comment by jcfernandez-890825** [comment]
I'm using version 2021.12.3. As for Pycharm version=2021.3.1 (Build #PY-213.6461.77, built on December 28, 2021).

The error appears when you hover on the primary="True" attribute.

Hover over the greyed True.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc have you look into this?

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 Yes, I fixed this issue. Please wait for the next version.

**Comment by jcfernandez-890825** [comment]
Thanks man, you are the best.
