### ISSUE TITLE
Lots of error and warnings when doing a XML attribute inheritance

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#58]
This is the XML code:
```
<?xml version="1.0" encoding="utf-8" ?>
<odoo>
    <record id="view_account_move_reversal" model="ir.ui.view">
        <field name="model">account.move.reversal</field>
        <field name="inherit_id" ref="account.view_account_move_reversal" />
        <field name="arch" type="xml">
            <button name="reverse_moves" position="attributes">
                <attribute name="confirm">This will cancel any active claim associated with selected invoice(s), do you agreed?</attribute>
            </button>
        </field>
    </record>
</odoo>
```

![image](https://user-images.githubusercontent.com/28876647/148959931-8971f124-83e9-400b-9e6b-043eb9488890.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Please check if you injected language to the text. If true, uninject it (Alt + Enter).

![Screenshot from 2022-01-11 21-33-10](https://user-images.githubusercontent.com/11208291/148962239-8bb913cd-d0f9-42c6-8d9f-fae0642698bf.png)

**Comment by jcfernandez-890825** [comment]
Wow, I just learn something new. I'm bookmarking this for myself ;)
