### ISSUE TITLE
Deduce parameter type from route parameters

### ISSUE THREAD

**Issue by eselimsen** [trinhanhngoc/pycharm-odoo#60]
Hi
First of all, thank you for your work, I love this addon it works great and helps a lot on Odoo development.

For the issue, actually a feature request, as you know Odoo implements url converters for model related routes, so that you can define routes like `/slide/<model('slide.slide'):slide>` and you'll get slide with given id as your route parameter.
Can we deduce route parameter type from this definition?

I saw your message [here](https://github.com/odoo-ide/pycharm-odoo/issues/12#issuecomment-914451346), using this for now, but I think it would be great to have this feature.
Thanks

Some related links:
[Werkzeug custom converter docs](https://werkzeug.palletsprojects.com/en/0.16.x/routing/#custom-converters)
[Odoo model converter definition](https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/models/ir_http.py#L38)

**Comment by ghost** [comment]
Hi @eselimsen 

What Odoo plugin version are you using? This feature was implemented a long time ago.

![Screenshot from 2022-01-14 20-23-51](https://user-images.githubusercontent.com/65052910/149522181-26283054-8a40-4d59-bbb1-b4b2acffb1f6.png)

**Comment by eselimsen** [comment]
Ah, that's quite interesting.
After seeing your example, I tried this, and it worked:
`<model("slide.slide"):slide>` instead of
`<model('slide.slide'):slide>`

so it looks like it can't deduce the type when single quotes used.

**Comment by trinhanhngoc** [comment]
@eselimsen Thank you for your report. I have just been fixed the issue with single quotes. The fix will be available in the next version.

**Comment by eselimsen** [comment]
Thank you!

May I ask if there is a way to type annotate parameters or return values?
For example:
`def _update_partners(self, partner: "env['res.partner']")`

a definition like
`def _update_partners(self, partner: "res.partner")`
would probably clash with modules, imports etc but, maybe there's a way to "decorate" it or something?

**Comment by trinhanhngoc** [comment]
> Thank you!
> 
> May I ask if there is a way to type annotate parameters or return values? For example: `def _update_partners(self, partner: "env['res.partner']")`
> 
> a definition like `def _update_partners(self, partner: "res.partner")` would probably clash with modules, imports etc but, maybe there's a way to "decorate" it or something?

Yes, you can. E.g.

```python

from odoo.addons.base.models.res_partner import Partner

def _update_partners(self, partner: Partner):
    pass
```

Type of `partner` will be converted from `Partner` to `res.partner`.

**Comment by eselimsen** [comment]
Yes, but including every module or model just for type hinting looks a bit overkill for me, tried this and docs param methods in the past.
I thought maybe there's a way to implement such a shortcut, that would be great.

**Comment by trinhanhngoc** [comment]
> Yes, but including every module or model just for type hinting looks a bit overkill for me, tried this and docs param methods in the past. I thought maybe there's a way to implement such a shortcut, that would be great.

Yes, I think it can be implemented as the following example:

```python
def _update_partners(self, partner: "model:res.partner"):
    pass
```

The `model:` prefix is neccessary to distinguish Odoo model type from other types. What do you think?

**Comment by trinhanhngoc** [comment]
cc @jcfernandez-890825

**Comment by eselimsen** [comment]
> > Yes, but including every module or model just for type hinting looks a bit overkill for me, tried this and docs param methods in the past. I thought maybe there's a way to implement such a shortcut, that would be great.
> 
> Yes, I think it can be implemented as the following example:
> 
> ```python
> def _update_partners(self, partner: "model:res.partner"):
>     pass
> ```
> 
> The `model:` prefix is neccessary to distinguish Odoo model type from other types. What do you think?

Yes, looks very nice to me.

**Comment by jcfernandez-890825** [comment]
> > Yes, but including every module or model just for type hinting looks a bit overkill for me, tried this and docs param methods in the past. I thought maybe there's a way to implement such a shortcut, that would be great.
> 
> Yes, I think it can be implemented as the following example:
> 
> ```python
> def _update_partners(self, partner: "model:res.partner"):
>     pass
> ```
> 
> The `model:` prefix is neccessary to distinguish Odoo model type from other types. What do you think?

+1 to this.
I was getting a little annoyed having to use docstrings just to define type hints for method parameters hehe. (Yes, I know I should do docstring for everything, pylint always complains about it)
![image](https://user-images.githubusercontent.com/28876647/149635895-a6d05f7f-479b-4d4e-bb67-e242fb212e96.png)

Maybe with this we can finally use multi-type hints?

**Comment by eselimsen** [comment]
We should be able to use Union to apply multi-type hints when implemented, would be quite useful for especially return values:
`def _get_available_partner(self) -> Union["model:res.partner", False]`

Know it may be a bit too much for now but, we may even be able to add some prefix or something to denote recordset state too, empty, single or multi !
Maybe something like,
`"model:res.partner"`, `"model_empty:res.partner"`, `"model_one:res.partner"`, `"model_multi:res.partner"`

Don't think would matter much for IDE, but it would be pretty useful for developers.

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released with a fix for the issue with single quotes. For further discussion about type hint, we should continue at https://github.com/odoo-ide/pycharm-odoo/issues/12. Thanks!
