### ISSUE TITLE
Ignore setup folder in OCA repositories

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#63]
Almost every single OCA repository comes with a setup folder which has the modules and code. This causes to put extra results when you do Ctrl+Clic. Is there a way to ignore this folders?

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Could you give me a screenshot of the problem with code navigation  (Ctrl+Click)?

**Comment by jcfernandez-890825** [comment]
![image](https://user-images.githubusercontent.com/28876647/150538162-9795a1c1-fbc2-4d4f-8f87-467bab7bd65b.png)


![image](https://user-images.githubusercontent.com/28876647/150539799-086a1265-e413-4451-899b-fcf694b6f161.png)


The only way I have come up with for stopping this is to mark those setup folder as excluded, but there are 68 OCA repositories, so it becomes a very tedious task every time I have to setup a new project.
😅

**Comment by trinhanhngoc** [comment]
=)) This will be fixed in the next version.

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released.
