### ISSUE TITLE
Unresolved attribute reference '__get_bank_statements_available_sources' for class 'account.journal' 

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#64]
I'm getting this error in Odoov14EE

![image](https://user-images.githubusercontent.com/28876647/150617205-95e178fb-a7dd-425c-a655-b4014a6ee9e2.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

This issue has just been fixed. Please wait for the next version. Thank you again!

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released.
