### ISSUE TITLE
Cannot resolve symbol 'boolean_button'

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#65]
![image](https://user-images.githubusercontent.com/28876647/150788504-f91cc583-3fc3-455c-b775-52bc4cd21ba8.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The widget `boolean_button` has been removed since Odoo 13. See this PR: https://github.com/odoo/odoo/pull/34496

**Comment by jcfernandez-890825** [comment]
Yet, as you can see there are still used in several OCA modules in v14.
There's even a reference here `src/odoo/odoo/addons/web/static/src/scss/list_view.scss`
```
.o_data_row:not(.o_selected_row) .o_data_cell {

            // Boolean fields in non-selected rows completely disabled.
            .custom-checkbox {
                pointer-events: none;
            }

            // These widgets enable the checkbox if there is no readonly modifier.
            &.o_boolean_button_cell,
            &.o_boolean_favorite_cell,
            &.o_boolean_toggle_cell,
            &.o_toggle_button_cell {

                &:not(.o_readonly_modifier) .custom-checkbox {
                    pointer-events: auto;
                }
            }
        }
```

**Comment by trinhanhngoc** [comment]
Uhm, I think those modules need to be updated to adapt to the changes.
