### ISSUE TITLE
Allow searching and navigation for "active_model" in self._context or self.env.context

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#66]
![image](https://user-images.githubusercontent.com/28876647/150988630-4e49f096-4626-47fa-b6b4-9bbdc046ce0d.png)

Also please allow autocomplete for "active_model", "active_id", "active_ids" in self._context or self.env.context.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

I just implemented these features. Please wait for the next version.

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released.
