### ISSUE TITLE
Look for field usages in _sql_constraints. Implement code navigation, and searching appearances 

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#69]
![image](https://user-images.githubusercontent.com/28876647/151808954-db43e1b7-eae6-4ac4-9ad5-9bc3ab665719.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

In the next version, we will have these great features =))

<img width="1116" alt="Screen Shot 2022-02-05 at 15 28 01" src="https://user-images.githubusercontent.com/11208291/152634554-4180caff-2817-435a-a1c3-b1d73646eb42.png">

**Comment by jcfernandez-890825** [comment]
You really know how to make people happy

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released.
