### ISSUE TITLE
Code navigation for "default_model" attribute in "res.config.settings" module inherits.

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#70]
![image](https://user-images.githubusercontent.com/28876647/151859407-2ef98e31-db84-4e80-b701-6d456e35beb4.png)

Also, for "Selections" fields, code navigation on default attribute doesn't work.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

I just implemented these features. Please wait for the next version.

**Comment by jcfernandez-890825** [comment]
> Please wait for the next version.

I missed this phrase of yours @trinhanhngoc 

I can't wait, for the new release.

**Comment by trinhanhngoc** [comment]
The new version 2022.1 just released.
