### ISSUE TITLE
Autocomplete commercial modules like sale.subscription?

### ISSUE THREAD

**Issue by psy0rz** [trinhanhngoc/pycharm-odoo#72]
Does/should it auto complete this?

e.g., this works:

![image](https://user-images.githubusercontent.com/1179017/154140638-e706a477-8747-47ab-bf47-ae184c980509.png)

but this doesnt:

![image](https://user-images.githubusercontent.com/1179017/154140682-8c5a7333-e67f-42fd-8147-725d3c832444.png)

I've added the whole commercial odoo tree to the project and reindexed the whole project.

Does it only have a limited amount of build-in autocompletion, or should it auto complete any valid odoo add-on?

Thanks!

(Awesome pycharm plugin btw!)

**Comment by trinhanhngoc** [comment]
@psy0rz Yes, it should auto complete any valid odoo-addon. Please make sure that you have declared `sale_subscription` as a depend in the `__manifest__.py` of your odoo module.

**Comment by psy0rz** [comment]
awesome, it works! thanks

**Comment by psy0rz** [comment]
well this plugin is amazing! im still using the demo, but i will buy a license when im done with this customer project. 

it transforms developing in odoo from a frustrating guessing/lookup/search game, to a relaxing experience with autocomplete  :)

**Comment by jcfernandez-890825** [comment]
@psy0rz you mix this wonder with [TabNine](https://www.tabnine.com/) and templates for boilerplate code (odoo imports, xml views, module/field definition, etc) and you get a Batman/Ironman with Kryptonian/Asgardian DNA that beats the crap out of any developing issue you might face.

@trinhanhngoc keep up giving us mortal developers this godlike tool.

**Comment by psy0rz** [comment]
cool will try tabnine. 

i'm just browsing the odoo sources to look at existing addons (since i have my project referencing to them anyway)

especially usefull to figure out how to intergrate with the enduser portal.
