### ISSUE TITLE
Missing imports are not highlighted

### ISSUE THREAD

**Issue by robin5210** [trinhanhngoc/pycharm-odoo#73]
The following code snippet should highlight missing imports:

```
class TestModel(models.Model):
    _name = "test.model"
    _description = "Test Model"

    name = fields.Char()
```

With Odoo addon active:
![Screenshot from 2022-02-16 09-04-09](https://user-images.githubusercontent.com/3855197/154222105-67561294-f830-4870-8b4e-92c0ea77ca94.png)

Without Odoo addon active:
![Screenshot from 2022-02-16 09-07-12](https://user-images.githubusercontent.com/3855197/154222134-2047ee01-1a9a-4767-a930-ba193d741194.png)

My environment:

Ubuntu 20.04
PyCharm 2021.3.2 (Professional Edition) installed via snap

**Comment by trinhanhngoc** [comment]
Hi @robin5210 

This is so weird. No problem on my PyCharm Professional 2021.3.2 with the Odoo plugin.

<img width="332" alt="Screen Shot 2022-02-16 at 15 15 13" src="https://user-images.githubusercontent.com/11208291/154223662-3313a614-3a28-42bd-a8aa-e714e001497e.png">

**Comment by robin5210** [comment]
I have reinstalled PyCharm and deleted all PyCharm data from my system. This seems to have solved the problem :)
