### ISSUE TITLE
false positive for "id" attribute on model instances

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#76]
module version 2022.1

<img width="588" alt="Screenshot 2022-03-17 at 10 25 52" src="https://user-images.githubusercontent.com/199073/158779274-b545eb3b-f274-4410-a683-079b4240bad3.png">

**Comment by trinhanhngoc** [comment]
Hi @jerzyk 

Did you attach [Odoo Stubs](https://github.com/odoo-ide/odoo-stubs) to your project? You can read the following documentation: https://odoo-ide.com/docs/pycharm.

**Comment by jerzyk** [comment]
yes, and it was working for one project, but not for the second one:

<img width="572" alt="Screenshot 2022-03-17 at 13 06 18" src="https://user-images.githubusercontent.com/199073/158805174-dc1d246e-cf0c-4081-858c-cb12c29fd5ef.png">

**Comment by jerzyk** [comment]
even after index rebuild

**Comment by trinhanhngoc** [comment]
@jerzyk Can you provide a screenshot of your project structure? E.g.

![image](https://user-images.githubusercontent.com/11208291/158836413-91ed864e-fecb-4dcf-9bc0-b779dd522b37.png)

**Comment by jerzyk** [comment]
sure

<img width="740" alt="Screenshot 2022-03-17 at 17 10 41" src="https://user-images.githubusercontent.com/199073/158844448-81c866d7-da62-4fc8-ad69-18073608e9dc.png">

**Comment by trinhanhngoc** [comment]
@jerzyk , you must add `dev14/odoo-stub14` instead of `dev14/odoo-stub14/odoo-stubs` as the content root. This is how PyCharm discovers the corresponding stubs for a python package.

**Comment by jerzyk** [comment]
that was it, thanks!
