### ISSUE TITLE
false positive unresolved reference

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#77]
in a statement 

```
self.env['xxx'].search([], order='is_default DESC NULLS LAST', limit=1)
```

`NULLS` is being highlighted as unresolved reference:

<img width="536" alt="Screenshot 2022-04-11 at 11 58 15" src="https://user-images.githubusercontent.com/199073/162714930-73ed3041-07fd-4496-8574-e7ed325d8ab6.png">
e

**Comment by trinhanhngoc** [comment]
Hi @jerzyk . Thank you for reporting. This issue has just been fixed. Please wait for the next version. Thanks.

**Comment by jerzyk** [comment]
thanks!
