### ISSUE TITLE
Type hint for recordset not working when declared with # type: model.name

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#78]
![image](https://user-images.githubusercontent.com/28876647/162780075-0285adc9-389e-4db4-bcaf-463ccf806f80.png)

![image](https://user-images.githubusercontent.com/28876647/162779827-ffc53a0a-c919-49b4-9303-f784a71080aa.png)

**Comment by trinhanhngoc** [comment]
See also #12

**Comment by jcfernandez-890825** [comment]
So ... This is still a pending feature ?

**Comment by trinhanhngoc** [comment]
> So ... This is still a pending feature ?

Yes. I will revisit this feature after releasing the next version in this month. Please be patient :)))

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The new version 2022.6 has been released with the support for this type hint syntax.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 

Quick question, using the new type hint feature, how can I define var `m2x_dct_lst` type as a dictionary list to be used for `m2x.create.edit.option` record creation? I wanted to use code completion while creating this list comprehension, but failed.

```python
from odoo import SUPERUSER_ID
from odoo.api import Environment
from odoo.sql_db import Cursor

env = Environment(Cursor('pool', 'dbname', 'dsn'), SUPERUSER_ID, {})
self = env['res.users']


fld_rs = self.env['ir.model.fields'].search([
    ('relation', 'in', ('product.product', 'product.template')),
    ('ttype', 'in', ('many2many', 'many2one')),
])

m2x_dct_lst = [
    {
        'field_id': fld.id,
        'model_id': fld.model_id.id,
        'option_create': 'force_false',
        'option_create_edit': 'force_false',
        'option_create_edit_wizard': False,
    }
    for fld in fld_rs
]  # type: list[dict]

self.env['m2x.create.edit.option'].search([]).unlink()
self.env['m2x.create.edit.option'].create(m2x_dct_lst)

self.env.cr.commit()

```

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 Do you mean type hint for recordset values ?

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 
I think so? If I put the list comprehension directly into the `create` method then I get code completion. Like this

```python
# ...

self.env['m2x.create.edit.option'].create([
    {
        'field_id': fld.id,
        'model_id': fld.model_id.id,
        'option_create': 'force_false',
        'option_create_edit': 'force_false',
        'option_create_edit_wizard': False,
    }
    for fld in fld_rs
])

# ...
```

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 After you type `self.env['m2x.create.edit.option'].create([{`, the plugin knows that you are creating recordsets for the model `m2x.create.edit.option` so code completion should work as expected. However, when you define recordset values before passing to `create()`, the plugin can not guess the model without type hint. As I commented in #12, I'm still looking for a syntax that is efficient and elegant enough to use for recordset values type hint. If you have any ideas or proposals, please let me know.

**Comment by jcfernandez-890825** [comment]
Well I do like this one `odoo.model_dict.res_partner`, though this one is not bad either `Annotated[dict, odoo.model.sale_order_line]`. Like I said, do one and then work on either the others or improve the one existing.

In the meantime I can just define the list comprehension in the create method and then, once is finished, moved to the variable hehe.
