### ISSUE TITLE
Navigation (Ctrl+Click) feature for Website.viewref method

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#81]
Is for this method 
```
request.env['website'].viewref(...)
request.website.viewref(...)

Environment['website'].viewref(...)
odoo/addons/website/models/website.py/Website.viewref(...)
```

Currently is not working
![image](https://user-images.githubusercontent.com/28876647/165547167-d44c8ee0-d13f-4bd9-8d42-069076bd58fc.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825. This will be improved in the next version. Please wait a few days for the new version.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , the new version has been released.
