### ISSUE TITLE
Slows Pycharm

### ISSUE THREAD

**Issue by KKamaa** [trinhanhngoc/pycharm-odoo#83]
Hello, I noticed that the addon even paid copy slows pycharm and eats alot of memory. It seems there is a bug in the plugin

**Comment by trinhanhngoc** [comment]
> Hello, I noticed that the addon even paid copy slows pycharm and eats alot of memory. It seems there is a bug in the plugin

Can you please provide more information such as: PyCharm version, Odoo plugin version, your hardware info, memory consumption info?

**Comment by KKamaa** [comment]
> > Hello, I noticed that the addon even paid copy slows pycharm and eats alot of memory. It seems there is a bug in the plugin
> 
> Can you please provide more information such as: PyCharm version, Odoo plugin version, your hardware info, memory consumption info?

I realized that it was due to Pycharm Pro version its heavy and can consume a lot of resources due to its many features. Community handles the load well so will close this.
