### ISSUE TITLE
Support for Odoo Fork called "Flectra"

### ISSUE THREAD

**Issue by renzo1974** [trinhanhngoc/pycharm-odoo#88]
We have switched from Odoo to Flectra 2 years ago.

Your plugin is also working nice with flectra... but not fully.
Would be great to have this plugin also for flectra (see https://flectrahq.com).

If this is not possible or wanted, maybe you can give us some tipps what is needed to have 99% compatibility for flectra.

PS: Flectra 2.0 is based on Odoo 14.0. Everything called Odoo is renamed to flectra. This is the only change.

**Comment by trinhanhngoc** [comment]
Hi @rm-jamotion I love to support Odoo forks too. Please wait for the next version with initial support for Flectra.

**Comment by jcfernandez-890825** [comment]
Is itn't Flectra the copycat that got sued?

**Comment by trinhanhngoc** [comment]
> Is itn't Flectra the copycat that got sued?

Hi @jcfernandez-890825 I also heard about that but I'm not sure what the current situation is.

**Comment by renzo1974** [comment]
@jcfernandez-890825 this case was closed in middle of 2018 (see https://medium.com/@parthivpatel_26549/the-great-copyright-suit-of-odoo-vs-flectra-and-the-conclusion-698c9f6facc7). Odoo has stopped the request and paid 3/4 of all costs. This was the day where me and my whole team switched from odoo to flectra (currently 4 employee using this plugin).  Today in Switzerland flectra is growing very fast.

**Comment by renzo1974** [comment]
@trinhanhngoc this are very good news. Is this also made for vscode? I have some partners using vsc so I will promote the flectra support when available to support your great work!

**Comment by jcfernandez-890825** [comment]
@rm-jamotion 
From the technical point of view. Why changing coats?

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc this are very good news. Is this also made for vscode? I have some partners using vsc so I will promote the flectra support when available to support your great work!

Yes, support for VSCode is already on my roadmap.

**Comment by renzo1974** [comment]
@jcfernandez-890825 I was an odoo partner years ago and liked their work. But beginning with odoo 9.0 more and more features where removed from CE. And many cool features made by the community are added to EE with more or less the same OpenSource code, but than unter OPL license.
So my decision was not based on technical points but on strategy and how odoo will work together with community.

And flectra has reimplemented so many features that are lost in odo CE (e.g. Payroll, full accounting, credit control, ...)

**Comment by renzo1974** [comment]
> Hi @rm-jamotion I love to support Odoo forks too. Please wait for the next version with initial support for Flectra.

Hi @trinhanhngoc 

Are there any news on flectra support?
We have 4 licenses of your plugin.

Since last update, the benefit for us flectra developers has decreased massively (e.g. no more CTRL+click support on models). 
Older releases did help us also. But not I think we loose more and more features in flectra dev...

So I'm thinking about buying the four licenses for next year. Are there any hopefully good news for flectra support in the next few months?

**Comment by trinhanhngoc** [comment]
Hi @rm-jamotion 

Yes, support for Flectra is already on my roadmap. However, I am currently busy with some important features and refactoring that will be released in the next few days. After that, I will start working on Flectra support. You can help me by describing in detail what is not working in this issue.

**Comment by renzo1974** [comment]
First of all I have created the debugger repository to support flectra.
You can find it here: https://github.com/jamotion/pydevd-flectra 
Feel free to fork this repo in your account. So I will remove my repository later.

I am not sure if odoo-stubs needs a refactoring to flectra-stubs where all odoo strings are replaced to flectra.

- When I e.g. click on a value of `comodel_name='account.move`' the link is no longer working.
- Clicking on fields is working nice. Clicking on `_inherit='account.move'` is also working as expected.
- In some cases, the click on a super method is also not working. 
- csv support is not working when writing e.g. model_xxx no list is showing

Maybe it's the most successful way to search for odoo and replace it to flectra?

**Comment by trinhanhngoc** [comment]
@rm-jamotion 

Ok.

1. **Debugger**: It looks like I will extend `pydevd-odoo` and release a new version to support Flectra.
2. **Stubs**: I need to build specific stubs for the Flectra source code. Also, I am planning to bundle the stubs with the plugin so it will simplify the setup process.
3. **Code analysis**: Some works need to be done to fully understand Flectra.

Because the plugin has a lot of features and I am working mainly with Odoo source code, feel free to describe in detail what is not working for Flectra and I will do my best to support it.

**Comment by trinhanhngoc** [comment]
Hi @rm-jamotion [`pydevd-odoo`](https://github.com/odoo-ide/pydevd-odoo) has been updated to support Flectra. You can get the new version by:

`pip install --upgrade pydevd-odoo`

The next step is improving the Odoo plugin for PyCharm to support Flectra.

**Comment by renzo1974** [comment]
Wow! Great!

Thank you very much!

PS: I have extended our 4 licenses of your odoo pycharm plugin... ;-)

**Comment by trinhanhngoc** [comment]
Flectra support checklist for the next version:

- [x] Improve `pydevd-odoo` to support Flectra.
- [x] Support Flectra XML files.
- [x] Support  import module from `flectra.addons`.
- [x] Support `comodel_name` value reference.
- [ ] Support model reference in `ir.model.access.csv` (could not reproduce the issue).
- [x] Support group reference in `ir.model.access.csv`.
- [x] Support JS Module

cc @rm-jamotion

**Comment by trinhanhngoc** [comment]
Hi @rm-jamotion 

The version 2022.5 has been released with the full support for Flectra!
