### ISSUE TITLE
Lots of errors on src/odoo/odoo/addons/base/data/res_country_data.xml

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#89]
For example:
![image](https://user-images.githubusercontent.com/28876647/171322088-23c7efe8-1b25-45ba-a2c7-8128821737a4.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

I confirmed this bug. This bug will be fixed in the next version. Thank you very much.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2022.4 has been released with the fix for this issue.
