### ISSUE TITLE
Unresolved reference 'unique' 

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#91]
src/odoo/odoo/addons/payment_test/models/account_payment_method.py
![image](https://user-images.githubusercontent.com/28876647/172437191-741b7041-210d-434c-b07e-f33ed85c06df.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 This issue was fixed. Please wait for the next version. Thank you.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2022.4 has been released with the fix for this issue.
