### ISSUE TITLE
Cannot resolve symbol ''

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#93]
Using XML I'm trying to do a update a "payment.acquirer" record:
![image](https://user-images.githubusercontent.com/28876647/173251780-53e3b59d-e192-444e-b39f-01322c6bae67.png)

This is the error on line 11:
![image](https://user-images.githubusercontent.com/28876647/173252073-7ab41e1c-0468-4e26-975d-96f5c73517e6.png)

This is the original record definition:
![image](https://user-images.githubusercontent.com/28876647/173252128-ae566551-9834-466b-a475-e0b6066f4037.png)

I think this error might be related to the fact that "support_refund" is a "Selection" field and I'm trying to set it as NULL/False.
![image](https://user-images.githubusercontent.com/28876647/173252175-9c1a481e-05dc-4ab2-a363-013d8b0629d8.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Sorry for the late reply. I have been very busy with many important improvements and refactoring for the plugin over the past two months. Anyway, this issue has been fixed. Please wait for the next version in the next week.

**Comment by jcfernandez-890825** [comment]
Thanks @trinhanhngoc. As always you are the best. Please keep improving this amazing plugin and I hope Odoo decides to offer you a big fat contract for doing this amazing feature.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2022.4 has been released with the fix for this issue.
