### ISSUE TITLE
Unresolved reference 'id'

### ISSUE THREAD

**Issue by AntoineVDV** [trinhanhngoc/pycharm-odoo#94]
Using the plugin Odoo 2022.3.1 with PyCharm 2022.1.2, I'm suddenly having lots of warning related to the `id` field.

For example, in https://github.com/odoo/odoo/blob/15.0/addons/payment/controllers/portal.py#L395, the plugin shows an incorrect "Unresolved reference 'id' " error.
![image](https://user-images.githubusercontent.com/15896813/173305820-129c9c97-be11-48e6-8e57-3953ef58c203.png)

Two lines below, it says "Unresolved attribute reference 'id' for class 'res.partner' ".

**Comment by trinhanhngoc** [comment]
Hi @AntoineVDV Have you attached **odoo-stubs** (https://github.com/odoo-ide/odoo-stubs) to your project yet?

**Comment by trinhanhngoc** [comment]
In the next version I will bundle **odoo-stubs** with the plugin so people will not need to manually attach it to their projects. For now, you still need to do it manually.

**Comment by AntoineVDV** [comment]
Yes, I have. `id` is the only field that triggers warnings, and it does in every file.

**Comment by trinhanhngoc** [comment]
> Yes, I have. `id` is the only field that triggers warnings, and it does in every file.

Please check your **odoo-stubs** if it's up to date. If the stub of `models.py` has `id` declaration as on the following link: https://github.com/odoo-ide/odoo-stubs/blob/56d5a83eda2f3966c652764dca72676af175c870/odoo-stubs/models.pyi#L93 , then it should work.

**Comment by trinhanhngoc** [comment]
Here is the screencast on my machine, no problems.

https://user-images.githubusercontent.com/11208291/173312615-f0eace48-d96d-4cfc-bebc-15f29d942ffe.mov

**Comment by AntoineVDV** [comment]
Yes, I pulled the latest changes on branch `master` and restarted PyCharm before filling this issue. I also tried to play with the 'Project Structure' settings but without success. I had no issue with the `id` field before a few days ago. Could it be related to the PyCharm version?

**Comment by trinhanhngoc** [comment]
> Yes, I pulled the latest changes on branch `master` and restarted PyCharm before filling this issue. I also tried to play with the 'Project Structure' settings but without success. I had no issue with the `id` field before a few days ago. Could it be related to the PyCharm version?

It's weird. I am also using PyCharm 2022.1.2 but no problems.

**Comment by AntoineVDV** [comment]
I'll wait for the new plugin version with the bundled stubs and hope that it fixes the issue :)

**Comment by trinhanhngoc** [comment]
> I'll wait for the new plugin version with the bundled stubs and hope that it fixes the issue :)

Yes. In the meantime, you can try **Invalidate Caches** (https://www.jetbrains.com/help/pycharm/invalidate-caches.html) if it fixes your problem.

**Comment by jcfernandez-890825** [comment]
Then, on next version. Should we detach **odoo-stubs** from every Odoo project?

**Comment by trinhanhngoc** [comment]
> Then, on next version. Should we detach **odoo-stubs** from every Odoo project?

Yes!

**Comment by AntoineVDV** [comment]
Hello @trinhanhngoc, the problem persists even on a fresh Ubuntu install with a brand new odoo/odoo project. I am now using PyCharm 2022.2 and the Odoo plugin in version 2022.4. Could you fix this, please?

**Comment by trinhanhngoc** [comment]
> Hello @trinhanhngoc, the problem persists even on a fresh Ubuntu install with a brand new odoo/odoo project. I am now using PyCharm 2022.2 and the Odoo plugin in version 2022.4. Could you fix this, please?

I have got a solution for this issue. Please wait for the fix in the next version.

**Comment by trinhanhngoc** [comment]
Hi @AntoineVDV 

The version 2022.5 has been released with the fix for this issue.

**Comment by jcfernandez-890825** [comment]
Does this mean that we have to detach `odoo-stubs` ?

**Comment by AntoineVDV** [comment]
Hello, I confirm that the bug is fixed with 2022.5.

**Comment by trinhanhngoc** [comment]
> Does this mean that we have to detach `odoo-stubs` ?

@jcfernandez-890825  Not yet. I will let you know when we can detach it.
