### ISSUE TITLE
instance attribute defined outside __init__

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#96]
I have a false positive warning,  when trying to extend account.move model

in the whole file, there are 2 warnings when I'm trying to assign value to `self.currency_id` and `self.invoice_origin` (both fields updated in `onchange` methods.

<img width="855" alt="Screenshot 2022-07-25 at 07 53 01" src="https://user-images.githubusercontent.com/199073/180708915-c36f6c89-f661-4294-bdfe-9e019b67333b.png">

odoo14 + enterprise, stubs are up to date and properly linked to the project, tried full reindex (with clear cache) - warnings on PyCharm 2022.1.4 and 2022.2RC

**Comment by trinhanhngoc** [comment]
Hi @jerzyk 

I was able to reproduce these warnings. To workaround this issue, you can rename your onchange methods to start with an underscore `_` while waiting for a properly fix from the Odoo plugin. Thanks for your feedback.

**Comment by trinhanhngoc** [comment]
Also, this is the default behavior of PyCharm. Need the intervention from the Odoo plugin for PyCharm to know this is normal in the Odoo source code.

**Comment by trinhanhngoc** [comment]
Hi @jerzyk 

The version 2022.5 has been released with the fix for this issue.
