### ISSUE TITLE
Improvements for Go to symbol... for http routes

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#97]
When using variables or class attributes (Ex: `_accept_url`) on http routes, the feature `Go to symbol... for http routes` can't find those routes.

`odoo/addons/payment_transfer/controllers/main.py` on Odoo15
![image](https://user-images.githubusercontent.com/28876647/181261362-431a5912-8c1b-45b0-b468-f71d3d3a3e55.png)

![image](https://user-images.githubusercontent.com/28876647/181260979-ac1efb3b-a1c7-495f-9935-acb877252cfa.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The version 2022.5 has been released with improvements for this issue.

**Comment by jcfernandez-890825** [comment]
As usual, thanks for making the best plugin to ease working with Odoo. I hope you get rich.
