### ISSUE TITLE
Support for third-party theme inheritance

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#98]
Odoo templates created on modules starting with `theme_` cannot be inherited using the usual code:
```
<template id="product_catg_test_extended" inherit_id="theme_test.product_catg_test" name="Test">
    <xpath expr="//t[@t-if='categories']" position="replace"></xpath>
</template>
```

As such code gives the following error:
```
odoo.tools.convert.ParseError: "Element '' cannot be located in parent view
```

This happens due to this method `odoo/tools/convert.py/xml_import._tag_template`
```
def _tag_template(self, el):
    # Some coding

    if self.module.startswith('theme_'):
        model = 'theme.ir.ui.view'
    else:
        model = 'ir.ui.view'

    # More coding
```

As suggested [here](https://stackoverflow.com/questions/63648026/cant-inherit-odoo-theme-template). To make a proper inheritance, without creating our own "theme_" module, we have to do something like this:
```
<record id="product_catg_test_extended" model="ir.ui.view">
    <field name="name">product_catg_test_extended</field>
    <field name="inherit_id" search="[('key', '=', 'theme_test.product_catg_test')]"/>
    <field name="type">qweb</field>
    <field name="key">test_theme_extended.product_catg_test_extended</field>
    <field name="arch" type="xml">
        <xpath expr="//t[@t-if='categories']" position="replace"></xpath>
    </field>
</record>
```

Currently the plugin doesn't provide much help for this situation. Could you add support for this case?

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 OK. Please wait for this feature in the next release.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The version 2022.5 has been released with improvements for this case.

**Comment by jcfernandez-890825** [comment]
JIT, I have been dealing with 3rd party theme modules modification lately. You are the best.
