### ISSUE TITLE
XML error: Cannot resolve symbol 'xpath'

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#99]
`odoo/addons/mass_mailing/views/mailing_mailing_views.xml`
![image](https://user-images.githubusercontent.com/28876647/183460514-b92d5ee1-2e93-46eb-a2ee-851f2ac54061.png)

**Comment by trinhanhngoc** [comment]
This is also known as the `move` feature. https://www.odoo.com/documentation/15.0/developer/reference/backend/views.html#inheritance-specs

**Comment by trinhanhngoc** [comment]
In the next release, the Odoo plugin will have full support for the move node inheritance.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/11208291/186459368-79442930-c26e-4917-9daa-f380bd7a3e40.png">

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The version 2022.5 has been released with the fix for this issue.
